// logo_metrics.h -- GENERATED by scripts/gen_logo.py. Do not hand-edit.
// Where the artwork sits inside aiohud_logo.raw. The canvas is a fixed power of two so the mip chain
// is exact, and the art is centred in it at whatever proportion the render happened to have -- so the
// header positions itself from these instead of from a magic number that a new render would break.
#pragma once
namespace aio {
static const int   LOGO_TEX_W = 1024, LOGO_TEX_H = 256;
static const float LOGO_ART_X0 = 0.00000f, LOGO_ART_X1 = 1.00000f;   // fractions of the texture width
static const float LOGO_ART_Y0 = 0.12109f, LOGO_ART_Y1 = 0.87500f;   // ... and of its height
} // namespace aio
