// job_track_gen.h -- GENERATED by scripts/gen_job_track.py (res/spells.lua + res/job_abilities.lua + GearSwap).
// Per-JOB list of trackable entries for the Timers "track per job" config checklist :
//   { status, recast, minLevel, category, name }. A BUFF spell has status>0 ; a job ABILITY may have a buff
//   status AND/OR a recast (cooldown) -- Steal/Mug have recast only. Spells are deduped by status.
#pragma once
namespace aio {
enum TrackCat { TC_REFRESH, TC_HASTE, TC_PROTECT, TC_REGEN, TC_ENSPELL, TC_BARSPELL, TC_GAIN, TC_SPIKES, TC_DEFENSE, TC_SONG, TC_GEO, TC_NINJUTSU, TC_BLUE, TC_BLU_BUFF, TC_BLU_PHYS, TC_BLU_MAG, TC_BLU_DEB, TC_ENHANCE, TC_HEAL, TC_NUKE, TC_ENFEEBLE, TC_DARK, TC_DIVINE, TC_SUMMON, TC_UTILITY, TC_ROLL, TC_SAMBA, TC_DANCE, TC_RUNE, TC_WARD, TC_STRAT, TC_BPACT, TC_JA, TC_FOOD, TC_AFTERMATH, TC_SIGNET, TC_CRAFT, TC_OTHER, TC_COUNT };
static const char* const TRACK_CAT_EN[TC_COUNT] = { "Refresh", "Haste / Flurry", "Protect / Shell", "Regen", "Enspells", "Barspells", "Gains", "Spikes", "Defensive", "Songs", "Geomancy", "Ninjutsu", "Blue Magic", "Blue: Buff", "Blue: Physical", "Blue: Magical", "Blue: Debuff", "Enhancing", "Healing", "Elemental", "Enfeebling", "Dark Magic", "Divine", "Summons", "Utility", "Rolls", "Sambas", "Dances", "Runes", "Wards", "Stratagems", "Blood Pacts", "Job Abilities", "Food", "Aftermath", "Signet", "Craft", "Other" };
static const char* const TRACK_CAT_FR[TC_COUNT] = { "Refresh", "Haste / Flurry", "Protect / Shell", "Regen", "Enchantements", "Barspells", "Gains", "Spikes", "Defensif", "Chants", "Geomancie", "Ninjutsu", "Magie Bleue", "Bleu: Buff", "Bleu: Physique", "Bleu: Magique", "Bleu: Debuff", "Amelioration", "Soins", "Elementaire", "Affaiblissement", "Magie Noire", "Divine", "Invocations", "Utilitaire", "Rolls", "Sambas", "Danses", "Runes", "Wards", "Stratagemes", "Pactes", "Aptitudes", "Nourriture", "Aftermath", "Signet", "Artisanat", "Autre" };
struct JobBuff { unsigned short status; unsigned short recast; unsigned short level; unsigned char cat; const char* name; };
static const JobBuff JT_WAR[] = {
    {44,0,1,32,"Mighty Strikes"},   // TC_JA
    {56,1,15,32,"Berserk"},   // TC_JA
    {57,3,25,32,"Defender"},   // TC_JA
    {68,2,35,32,"Warcry"},   // TC_JA
    {58,4,45,32,"Aggressor"},   // TC_JA
    {405,8,60,32,"Retaliation"},   // TC_JA
    {340,6,75,32,"Warrior's Charge"},   // TC_JA
    {435,9,77,32,"Restraint"},   // TC_JA
    {460,11,87,32,"Blood Rage"},   // TC_JA
    {490,254,96,32,"Brazen Rush"},   // TC_JA
    {0,5,5,32,"Provoke"},   // TC_JA
    {0,7,75,32,"Tomahawk"},   // TC_JA
};
static const JobBuff JT_MNK[] = {
    {46,0,1,32,"Hundred Fists"},   // TC_JA
    {60,14,15,32,"Dodge"},   // TC_JA
    {59,13,25,32,"Focus"},   // TC_JA
    {61,17,45,32,"Counterstance"},   // TC_JA
    {406,21,65,32,"Footwork"},   // TC_JA
    {341,20,75,32,"Formless Strikes"},   // TC_JA
    {88,19,75,32,"Mantra"},   // TC_JA
    {436,22,79,32,"Perfect Counter"},   // TC_JA
    {461,31,88,32,"Impetus"},   // TC_JA
    {491,254,96,32,"Inner Strength"},   // TC_JA
    {0,16,5,32,"Boost"},   // TC_JA
    {0,15,35,32,"Chakra"},   // TC_JA
    {0,18,41,32,"Chi Blast"},   // TC_JA
};
static const JobBuff JT_WHM[] = {
    {103,69,5,5,"Barstonra"},   // TC_BARSPELL
    {106,86,7,5,"Barsleepra"},   // TC_BARSPELL
    {105,71,9,5,"Barwatera"},   // TC_BARSPELL
    {107,87,10,5,"Barpoisonra"},   // TC_BARSPELL
    {108,88,12,5,"Barparalyzra"},   // TC_BARSPELL
    {102,68,13,5,"Baraera"},   // TC_BARSPELL
    {100,66,17,5,"Barfira"},   // TC_BARSPELL
    {109,89,18,5,"Barblindra"},   // TC_BARSPELL
    {101,67,21,5,"Barblizzara"},   // TC_BARSPELL
    {110,90,23,5,"Barsilencera"},   // TC_BARSPELL
    {104,70,25,5,"Barthundra"},   // TC_BARSPELL
    {112,92,39,5,"Barvira"},   // TC_BARSPELL
    {111,91,43,5,"Barpetra"},   // TC_BARSPELL
    {286,85,78,5,"Baramnesra"},   // TC_BARSPELL
    {39,55,10,8,"Aquaveil"},   // TC_DEFENSE
    {36,53,19,8,"Blink"},   // TC_DEFENSE
    {37,54,28,8,"Stoneskin"},   // TC_DEFENSE
    {0,28,5,22,"Banish"},   // TC_DIVINE
    {0,38,15,22,"Banishga"},   // TC_DIVINE
    {0,29,30,22,"Banish II"},   // TC_DIVINE
    {0,39,40,22,"Banishga II"},   // TC_DIVINE
    {0,112,45,22,"Flash"},   // TC_DIVINE
    {0,98,48,22,"Repose"},   // TC_DIVINE
    {0,21,50,22,"Holy"},   // TC_DIVINE
    {0,30,65,22,"Banish III"},   // TC_DIVINE
    {0,22,95,22,"Holy II"},   // TC_DIVINE
    {0,23,3,20,"Dia"},   // TC_ENFEEBLE
    {0,58,4,20,"Paralyze"},   // TC_ENFEEBLE
    {0,56,13,20,"Slow"},   // TC_ENFEEBLE
    {0,59,15,20,"Silence"},   // TC_ENFEEBLE
    {0,33,18,20,"Diaga"},   // TC_ENFEEBLE
    {0,24,36,20,"Dia II"},   // TC_ENFEEBLE
    {0,286,93,20,"Addle"},   // TC_ENFEEBLE
    {70,138,15,17,"Deodorize"},   // TC_ENHANCE
    {71,137,20,17,"Sneak"},   // TC_ENHANCE
    {69,136,25,17,"Invisible"},   // TC_ENHANCE
    {275,96,55,17,"Auspice"},   // TC_ENHANCE
    {0,143,32,17,"Erase"},   // TC_ENHANCE
    {0,123,36,17,"Teleport-Dem"},   // TC_ENHANCE
    {0,122,36,17,"Teleport-Holla"},   // TC_ENHANCE
    {0,124,36,17,"Teleport-Mea"},   // TC_ENHANCE
    {0,121,38,17,"Teleport-Altep"},   // TC_ENHANCE
    {0,120,38,17,"Teleport-Yhoat"},   // TC_ENHANCE
    {0,139,42,17,"Teleport-Vahzl"},   // TC_ENHANCE
    {0,81,53,17,"Recall-Jugner"},   // TC_ENHANCE
    {0,83,53,17,"Recall-Meriph"},   // TC_ENHANCE
    {0,82,53,17,"Recall-Pashh"},   // TC_ENHANCE
    {121,481,81,6,"Boost-VIT"},   // TC_GAIN
    {124,484,84,6,"Boost-MND"},   // TC_GAIN
    {86,485,87,6,"Boost-CHR"},   // TC_GAIN
    {122,482,90,6,"Boost-AGI"},   // TC_GAIN
    {119,479,93,6,"Boost-STR"},   // TC_GAIN
    {123,483,96,6,"Boost-INT"},   // TC_GAIN
    {120,480,99,6,"Boost-DEX"},   // TC_GAIN
    {33,57,40,1,"Haste"},   // TC_HASTE
    {113,135,25,18,"Reraise"},   // TC_HEAL
    {0,1,1,18,"Cure"},   // TC_HEAL
    {0,14,6,18,"Poisona"},   // TC_HEAL
    {0,15,9,18,"Paralyna"},   // TC_HEAL
    {0,2,11,18,"Cure II"},   // TC_HEAL
    {0,16,14,18,"Blindna"},   // TC_HEAL
    {0,7,16,18,"Curaga"},   // TC_HEAL
    {0,17,19,18,"Silena"},   // TC_HEAL
    {0,3,21,18,"Cure III"},   // TC_HEAL
    {0,12,25,18,"Raise"},   // TC_HEAL
    {0,20,29,18,"Cursna"},   // TC_HEAL
    {0,8,31,18,"Curaga II"},   // TC_HEAL
    {0,19,34,18,"Viruna"},   // TC_HEAL
    {0,18,39,18,"Stona"},   // TC_HEAL
    {0,93,40,18,"Cura"},   // TC_HEAL
    {0,4,41,18,"Cure IV"},   // TC_HEAL
    {0,9,51,18,"Curaga III"},   // TC_HEAL
    {0,13,56,18,"Raise II"},   // TC_HEAL
    {0,5,61,18,"Cure V"},   // TC_HEAL
    {0,95,61,18,"Esuna"},   // TC_HEAL
    {0,94,65,18,"Sacrifice"},   // TC_HEAL
    {0,140,70,18,"Raise III"},   // TC_HEAL
    {0,10,71,18,"Curaga IV"},   // TC_HEAL
    {0,6,80,18,"Cure VI"},   // TC_HEAL
    {0,474,83,18,"Cura II"},   // TC_HEAL
    {0,11,91,18,"Curaga V"},   // TC_HEAL
    {0,475,96,18,"Cura III"},   // TC_HEAL
    {0,494,99,18,"Arise"},   // TC_HEAL
    {0,893,1200,18,"Full Cure"},   // TC_HEAL
    {78,26,15,32,"Divine Seal"},   // TC_JA
    {418,30,40,32,"Afflatus Misery"},   // TC_JA
    {417,29,40,32,"Afflatus Solace"},   // TC_JA
    {453,32,83,32,"Divine Caress"},   // TC_JA
    {477,33,95,32,"Sacrosanctity"},   // TC_JA
    {492,254,96,32,"Asylum"},   // TC_JA
    {0,0,1,32,"Benediction"},   // TC_JA
    {0,28,75,32,"Devotion"},   // TC_JA
    {0,27,75,32,"Martyr"},   // TC_JA
    {0,503,90,19,"Impact"},   // TC_NUKE
    {40,43,7,2,"Protect"},   // TC_PROTECT
    {40,125,7,2,"Protectra"},   // TC_PROTECT
    {41,48,17,2,"Shell"},   // TC_PROTECT
    {41,130,17,2,"Shellra"},   // TC_PROTECT
    {42,108,21,3,"Regen"},   // TC_REGEN
};
static const JobBuff JT_BLM[] = {
    {0,230,10,21,"Bio"},   // TC_DARK
    {0,245,12,21,"Drain"},   // TC_DARK
    {0,247,25,21,"Aspir"},   // TC_DARK
    {0,264,25,21,"Tractor"},   // TC_DARK
    {0,231,35,21,"Bio II"},   // TC_DARK
    {0,252,45,21,"Stun"},   // TC_DARK
    {0,248,83,21,"Aspir II"},   // TC_DARK
    {0,881,550,21,"Aspir III"},   // TC_DARK
    {0,367,1200,21,"Death"},   // TC_DARK
    {0,220,3,20,"Poison"},   // TC_ENFEEBLE
    {0,254,4,20,"Blind"},   // TC_ENFEEBLE
    {0,258,7,20,"Bind"},   // TC_ENFEEBLE
    {0,253,20,20,"Sleep"},   // TC_ENFEEBLE
    {0,225,24,20,"Poisonga"},   // TC_ENFEEBLE
    {0,273,31,20,"Sleepga"},   // TC_ENFEEBLE
    {0,259,41,20,"Sleep II"},   // TC_ENFEEBLE
    {0,221,43,20,"Poison II"},   // TC_ENFEEBLE
    {0,274,56,20,"Sleepga II"},   // TC_ENFEEBLE
    {0,255,85,20,"Break"},   // TC_ENFEEBLE
    {0,365,95,20,"Breakga"},   // TC_ENFEEBLE
    {0,261,17,17,"Warp"},   // TC_ENHANCE
    {0,263,29,17,"Escape"},   // TC_ENHANCE
    {0,262,40,17,"Warp II"},   // TC_ENHANCE
    {0,241,55,17,"Retrace"},   // TC_ENHANCE
    {47,0,1,32,"Manafont"},   // TC_JA
    {79,38,15,32,"Elemental Seal"},   // TC_JA
    {437,39,76,32,"Mana Wall"},   // TC_JA
    {598,12,85,32,"Cascade"},   // TC_JA
    {229,35,95,32,"Manawell"},   // TC_JA
    {493,254,96,32,"Subtle Sorcery"},   // TC_JA
    {0,34,87,32,"Enmity Douse"},   // TC_JA
    {0,159,1,19,"Stone"},   // TC_NUKE
    {0,169,5,19,"Water"},   // TC_NUKE
    {0,154,9,19,"Aero"},   // TC_NUKE
    {0,144,13,19,"Fire"},   // TC_NUKE
    {0,189,15,19,"Stonega"},   // TC_NUKE
    {0,239,16,19,"Shock"},   // TC_NUKE
    {0,149,17,19,"Blizzard"},   // TC_NUKE
    {0,238,18,19,"Rasp"},   // TC_NUKE
    {0,199,19,19,"Waterga"},   // TC_NUKE
    {0,237,20,19,"Choke"},   // TC_NUKE
    {0,164,21,19,"Thunder"},   // TC_NUKE
    {0,236,22,19,"Frost"},   // TC_NUKE
    {0,184,23,19,"Aeroga"},   // TC_NUKE
    {0,235,24,19,"Burn"},   // TC_NUKE
    {0,160,26,19,"Stone II"},   // TC_NUKE
    {0,240,27,19,"Drown"},   // TC_NUKE
    {0,174,28,19,"Firaga"},   // TC_NUKE
    {0,170,30,19,"Water II"},   // TC_NUKE
    {0,179,32,19,"Blizzaga"},   // TC_NUKE
    {0,155,34,19,"Aero II"},   // TC_NUKE
    {0,194,36,19,"Thundaga"},   // TC_NUKE
    {0,145,38,19,"Fire II"},   // TC_NUKE
    {0,190,40,19,"Stonega II"},   // TC_NUKE
    {0,150,42,19,"Blizzard II"},   // TC_NUKE
    {0,200,44,19,"Waterga II"},   // TC_NUKE
    {0,165,46,19,"Thunder II"},   // TC_NUKE
    {0,185,48,19,"Aeroga II"},   // TC_NUKE
    {0,206,50,19,"Freeze"},   // TC_NUKE
    {0,161,51,19,"Stone III"},   // TC_NUKE
    {0,208,52,19,"Tornado"},   // TC_NUKE
    {0,175,53,19,"Firaga II"},   // TC_NUKE
    {0,210,54,19,"Quake"},   // TC_NUKE
    {0,171,55,19,"Water III"},   // TC_NUKE
    {0,212,56,19,"Burst"},   // TC_NUKE
    {0,180,57,19,"Blizzaga II"},   // TC_NUKE
    {0,214,58,19,"Flood"},   // TC_NUKE
    {0,156,59,19,"Aero III"},   // TC_NUKE
    {0,204,60,19,"Flare"},   // TC_NUKE
    {0,195,61,19,"Thundaga II"},   // TC_NUKE
    {0,146,62,19,"Fire III"},   // TC_NUKE
    {0,191,63,19,"Stonega III"},   // TC_NUKE
    {0,151,64,19,"Blizzard III"},   // TC_NUKE
    {0,201,65,19,"Waterga III"},   // TC_NUKE
    {0,166,66,19,"Thunder III"},   // TC_NUKE
    {0,186,67,19,"Aeroga III"},   // TC_NUKE
    {0,162,68,19,"Stone IV"},   // TC_NUKE
    {0,176,69,19,"Firaga III"},   // TC_NUKE
    {0,172,70,19,"Water IV"},   // TC_NUKE
    {0,181,71,19,"Blizzaga III"},   // TC_NUKE
    {0,157,72,19,"Aero IV"},   // TC_NUKE
    {0,147,73,19,"Fire IV"},   // TC_NUKE
    {0,196,73,19,"Thundaga III"},   // TC_NUKE
    {0,152,74,19,"Blizzard IV"},   // TC_NUKE
    {0,213,75,19,"Burst II"},   // TC_NUKE
    {0,205,75,19,"Flare II"},   // TC_NUKE
    {0,215,75,19,"Flood II"},   // TC_NUKE
    {0,207,75,19,"Freeze II"},   // TC_NUKE
    {0,211,75,19,"Quake II"},   // TC_NUKE
    {0,167,75,19,"Thunder IV"},   // TC_NUKE
    {0,209,75,19,"Tornado II"},   // TC_NUKE
    {0,163,77,19,"Stone V"},   // TC_NUKE
    {0,173,80,19,"Water V"},   // TC_NUKE
    {0,499,81,19,"Stoneja"},   // TC_NUKE
    {0,158,83,19,"Aero V"},   // TC_NUKE
    {0,501,84,19,"Waterja"},   // TC_NUKE
    {0,148,86,19,"Fire V"},   // TC_NUKE
    {0,498,87,19,"Aeroja"},   // TC_NUKE
    {0,153,89,19,"Blizzard V"},   // TC_NUKE
    {0,496,90,19,"Firaja"},   // TC_NUKE
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,168,92,19,"Thunder V"},   // TC_NUKE
    {0,497,93,19,"Blizzaja"},   // TC_NUKE
    {0,219,94,19,"Comet"},   // TC_NUKE
    {0,500,96,19,"Thundaja"},   // TC_NUKE
    {0,218,99,19,"Meteor"},   // TC_NUKE
    {0,851,100,19,"Aero VI"},   // TC_NUKE
    {0,850,100,19,"Blizzard VI"},   // TC_NUKE
    {0,849,100,19,"Fire VI"},   // TC_NUKE
    {0,852,100,19,"Stone VI"},   // TC_NUKE
    {0,853,100,19,"Thunder VI"},   // TC_NUKE
    {0,854,100,19,"Water VI"},   // TC_NUKE
    {34,249,10,7,"Blaze Spikes"},   // TC_SPIKES
    {35,250,20,7,"Ice Spikes"},   // TC_SPIKES
    {38,251,30,7,"Shock Spikes"},   // TC_SPIKES
};
static const JobBuff JT_RDM[] = {
    {103,63,5,5,"Barstone"},   // TC_BARSPELL
    {106,72,7,5,"Barsleep"},   // TC_BARSPELL
    {105,65,9,5,"Barwater"},   // TC_BARSPELL
    {107,73,10,5,"Barpoison"},   // TC_BARSPELL
    {108,74,12,5,"Barparalyze"},   // TC_BARSPELL
    {102,62,13,5,"Baraero"},   // TC_BARSPELL
    {100,60,17,5,"Barfire"},   // TC_BARSPELL
    {109,75,18,5,"Barblind"},   // TC_BARSPELL
    {101,61,21,5,"Barblizzard"},   // TC_BARSPELL
    {110,76,23,5,"Barsilence"},   // TC_BARSPELL
    {104,64,25,5,"Barthunder"},   // TC_BARSPELL
    {112,78,39,5,"Barvirus"},   // TC_BARSPELL
    {111,77,43,5,"Barpetrify"},   // TC_BARSPELL
    {286,84,78,5,"Baramnesia"},   // TC_BARSPELL
    {0,230,10,21,"Bio"},   // TC_DARK
    {0,231,36,21,"Bio II"},   // TC_DARK
    {0,232,75,21,"Bio III"},   // TC_DARK
    {39,55,12,8,"Aquaveil"},   // TC_DEFENSE
    {36,53,23,8,"Blink"},   // TC_DEFENSE
    {116,106,33,8,"Phalanx"},   // TC_DEFENSE
    {37,54,34,8,"Stoneskin"},   // TC_DEFENSE
    {0,23,1,20,"Dia"},   // TC_ENFEEBLE
    {0,220,5,20,"Poison"},   // TC_ENFEEBLE
    {0,58,6,20,"Paralyze"},   // TC_ENFEEBLE
    {0,254,8,20,"Blind"},   // TC_ENFEEBLE
    {0,258,11,20,"Bind"},   // TC_ENFEEBLE
    {0,56,13,20,"Slow"},   // TC_ENFEEBLE
    {0,33,15,20,"Diaga"},   // TC_ENFEEBLE
    {0,59,18,20,"Silence"},   // TC_ENFEEBLE
    {0,216,21,20,"Gravity"},   // TC_ENFEEBLE
    {0,253,25,20,"Sleep"},   // TC_ENFEEBLE
    {0,24,31,20,"Dia II"},   // TC_ENFEEBLE
    {0,260,32,20,"Dispel"},   // TC_ENFEEBLE
    {0,841,35,20,"Distract"},   // TC_ENFEEBLE
    {0,843,42,20,"Frazzle"},   // TC_ENFEEBLE
    {0,221,46,20,"Poison II"},   // TC_ENFEEBLE
    {0,259,46,20,"Sleep II"},   // TC_ENFEEBLE
    {0,879,64,20,"Inundation"},   // TC_ENFEEBLE
    {0,276,75,20,"Blind II"},   // TC_ENFEEBLE
    {0,25,75,20,"Dia III"},   // TC_ENFEEBLE
    {0,80,75,20,"Paralyze II"},   // TC_ENFEEBLE
    {0,79,75,20,"Slow II"},   // TC_ENFEEBLE
    {0,286,83,20,"Addle"},   // TC_ENFEEBLE
    {0,842,85,20,"Distract II"},   // TC_ENFEEBLE
    {0,255,87,20,"Break"},   // TC_ENFEEBLE
    {0,844,92,20,"Frazzle II"},   // TC_ENFEEBLE
    {0,217,98,20,"Gravity II"},   // TC_ENFEEBLE
    {0,884,550,20,"Addle II"},   // TC_ENFEEBLE
    {0,882,550,20,"Distract III"},   // TC_ENFEEBLE
    {0,883,550,20,"Frazzle III"},   // TC_ENFEEBLE
    {70,138,15,17,"Deodorize"},   // TC_ENHANCE
    {71,137,20,17,"Sneak"},   // TC_ENHANCE
    {69,136,25,17,"Invisible"},   // TC_ENHANCE
    {432,493,95,17,"Temper"},   // TC_ENHANCE
    {98,104,16,4,"Enthunder"},   // TC_ENSPELL
    {97,103,18,4,"Enstone"},   // TC_ENSPELL
    {96,102,20,4,"Enaero"},   // TC_ENSPELL
    {95,101,22,4,"Enblizzard"},   // TC_ENSPELL
    {94,100,24,4,"Enfire"},   // TC_ENSPELL
    {99,105,27,4,"Enwater"},   // TC_ENSPELL
    {121,488,81,6,"Gain-VIT"},   // TC_GAIN
    {124,491,84,6,"Gain-MND"},   // TC_GAIN
    {125,492,87,6,"Gain-CHR"},   // TC_GAIN
    {122,489,90,6,"Gain-AGI"},   // TC_GAIN
    {119,486,93,6,"Gain-STR"},   // TC_GAIN
    {123,490,96,6,"Gain-INT"},   // TC_GAIN
    {120,487,99,6,"Gain-DEX"},   // TC_GAIN
    {581,845,48,1,"Flurry"},   // TC_HASTE
    {33,57,48,1,"Haste"},   // TC_HASTE
    {0,1,3,18,"Cure"},   // TC_HEAL
    {0,2,14,18,"Cure II"},   // TC_HEAL
    {0,3,26,18,"Cure III"},   // TC_HEAL
    {0,12,38,18,"Raise"},   // TC_HEAL
    {0,4,48,18,"Cure IV"},   // TC_HEAL
    {0,13,95,18,"Raise II"},   // TC_HEAL
    {48,0,1,32,"Chainspell"},   // TC_JA
    {419,50,50,32,"Composure"},   // TC_JA
    {454,36,83,32,"Saboteur"},   // TC_JA
    {230,37,95,32,"Spontaneity"},   // TC_JA
    {494,254,96,32,"Stymie"},   // TC_JA
    {0,49,40,32,"Convert"},   // TC_JA
    {0,159,4,19,"Stone"},   // TC_NUKE
    {0,169,9,19,"Water"},   // TC_NUKE
    {0,154,14,19,"Aero"},   // TC_NUKE
    {0,144,19,19,"Fire"},   // TC_NUKE
    {0,149,24,19,"Blizzard"},   // TC_NUKE
    {0,164,29,19,"Thunder"},   // TC_NUKE
    {0,160,35,19,"Stone II"},   // TC_NUKE
    {0,170,40,19,"Water II"},   // TC_NUKE
    {0,155,45,19,"Aero II"},   // TC_NUKE
    {0,145,50,19,"Fire II"},   // TC_NUKE
    {0,150,55,19,"Blizzard II"},   // TC_NUKE
    {0,165,60,19,"Thunder II"},   // TC_NUKE
    {0,161,65,19,"Stone III"},   // TC_NUKE
    {0,171,67,19,"Water III"},   // TC_NUKE
    {0,156,69,19,"Aero III"},   // TC_NUKE
    {0,146,71,19,"Fire III"},   // TC_NUKE
    {0,151,73,19,"Blizzard III"},   // TC_NUKE
    {0,166,75,19,"Thunder III"},   // TC_NUKE
    {0,162,77,19,"Stone IV"},   // TC_NUKE
    {0,172,80,19,"Water IV"},   // TC_NUKE
    {0,157,83,19,"Aero IV"},   // TC_NUKE
    {0,147,86,19,"Fire IV"},   // TC_NUKE
    {0,152,89,19,"Blizzard IV"},   // TC_NUKE
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,167,92,19,"Thunder IV"},   // TC_NUKE
    {0,158,100,19,"Aero V"},   // TC_NUKE
    {0,153,100,19,"Blizzard V"},   // TC_NUKE
    {0,148,100,19,"Fire V"},   // TC_NUKE
    {0,163,100,19,"Stone V"},   // TC_NUKE
    {0,168,100,19,"Thunder V"},   // TC_NUKE
    {0,173,100,19,"Water V"},   // TC_NUKE
    {40,43,7,2,"Protect"},   // TC_PROTECT
    {41,48,17,2,"Shell"},   // TC_PROTECT
    {43,109,41,0,"Refresh"},   // TC_REFRESH
    {42,108,21,3,"Regen"},   // TC_REGEN
    {34,249,20,7,"Blaze Spikes"},   // TC_SPIKES
    {35,250,40,7,"Ice Spikes"},   // TC_SPIKES
    {38,251,60,7,"Shock Spikes"},   // TC_SPIKES
};
static const JobBuff JT_THF[] = {
    {49,0,1,32,"Perfect Dodge"},   // TC_JA
    {65,64,15,32,"Sneak Attack"},   // TC_JA
    {32,62,25,32,"Flee"},   // TC_JA
    {87,66,30,32,"Trick Attack"},   // TC_JA
    {342,67,75,32,"Assassin's Charge"},   // TC_JA
    {343,68,75,32,"Feint"},   // TC_JA
    {462,40,87,32,"Conspirator"},   // TC_JA
    {0,60,5,32,"Steal"},   // TC_JA
    {0,65,35,32,"Mug"},   // TC_JA
    {0,63,45,32,"Hide"},   // TC_JA
    {0,69,65,32,"Accomplice"},   // TC_JA
    {0,69,65,32,"Collaborator"},   // TC_JA
    {0,61,77,32,"Despoil"},   // TC_JA
    {0,240,93,32,"Bully"},   // TC_JA
    {0,254,96,32,"Larceny"},   // TC_JA
};
static const JobBuff JT_PLD[] = {
    {116,106,77,8,"Phalanx"},   // TC_DEFENSE
    {274,310,85,22,"Enlight"},   // TC_DIVINE
    {0,28,7,22,"Banish"},   // TC_DIVINE
    {0,38,30,22,"Banishga"},   // TC_DIVINE
    {0,29,34,22,"Banish II"},   // TC_DIVINE
    {0,112,37,22,"Flash"},   // TC_DIVINE
    {0,21,55,22,"Holy"},   // TC_DIVINE
    {0,22,99,22,"Holy II"},   // TC_DIVINE
    {403,97,61,17,"Reprisal"},   // TC_ENHANCE
    {289,476,88,17,"Crusade"},   // TC_ENHANCE
    {0,1,5,18,"Cure"},   // TC_HEAL
    {0,2,17,18,"Cure II"},   // TC_HEAL
    {0,3,30,18,"Cure III"},   // TC_HEAL
    {0,12,50,18,"Raise"},   // TC_HEAL
    {0,4,55,18,"Cure IV"},   // TC_HEAL
    {50,0,1,32,"Invincible"},   // TC_JA
    {74,74,5,32,"Holy Circle"},   // TC_JA
    {62,75,30,32,"Sentinel"},   // TC_JA
    {114,76,35,32,"Cover"},   // TC_JA
    {93,77,62,32,"Rampart"},   // TC_JA
    {621,150,70,32,"Majesty"},   // TC_JA
    {344,78,75,32,"Fealty"},   // TC_JA
    {438,80,78,32,"Divine Emblem"},   // TC_JA
    {478,42,95,32,"Palisade"},   // TC_JA
    {0,73,15,32,"Shield Bash"},   // TC_JA
    {0,79,75,32,"Chivalry"},   // TC_JA
    {0,41,87,32,"Sepulcher"},   // TC_JA
    {0,254,96,32,"Intervene"},   // TC_JA
    {40,43,10,2,"Protect"},   // TC_PROTECT
    {41,48,20,2,"Shell"},   // TC_PROTECT
};
static const JobBuff JT_DRK[] = {
    {173,277,71,21,"Dread Spikes"},   // TC_DARK
    {288,311,85,21,"Endark"},   // TC_DARK
    {0,245,10,21,"Drain"},   // TC_DARK
    {0,230,15,21,"Bio"},   // TC_DARK
    {0,247,20,21,"Aspir"},   // TC_DARK
    {0,271,31,21,"Absorb-MND"},   // TC_DARK
    {0,264,32,21,"Tractor"},   // TC_DARK
    {0,272,33,21,"Absorb-CHR"},   // TC_DARK
    {0,268,35,21,"Absorb-VIT"},   // TC_DARK
    {0,269,37,21,"Absorb-AGI"},   // TC_DARK
    {0,252,37,21,"Stun"},   // TC_DARK
    {0,270,39,21,"Absorb-INT"},   // TC_DARK
    {0,231,40,21,"Bio II"},   // TC_DARK
    {0,267,41,21,"Absorb-DEX"},   // TC_DARK
    {0,266,43,21,"Absorb-STR"},   // TC_DARK
    {0,275,45,21,"Absorb-TP"},   // TC_DARK
    {0,242,61,21,"Absorb-ACC"},   // TC_DARK
    {0,246,62,21,"Drain II"},   // TC_DARK
    {0,248,78,21,"Aspir II"},   // TC_DARK
    {0,243,91,21,"Absorb-Attri"},   // TC_DARK
    {0,880,550,21,"Drain III"},   // TC_DARK
    {0,220,6,20,"Poison"},   // TC_ENFEEBLE
    {0,258,20,20,"Bind"},   // TC_ENFEEBLE
    {0,225,26,20,"Poisonga"},   // TC_ENFEEBLE
    {0,253,30,20,"Sleep"},   // TC_ENFEEBLE
    {0,221,46,20,"Poison II"},   // TC_ENFEEBLE
    {0,259,56,20,"Sleep II"},   // TC_ENFEEBLE
    {0,255,95,20,"Break"},   // TC_ENFEEBLE
    {51,0,1,32,"Blood Weapon"},   // TC_JA
    {75,86,5,32,"Arcane Circle"},   // TC_JA
    {64,87,15,32,"Last Resort"},   // TC_JA
    {63,85,30,32,"Souleater"},   // TC_JA
    {599,95,55,32,"Consume Mana"},   // TC_JA
    {345,89,75,32,"Dark Seal"},   // TC_JA
    {346,90,75,32,"Diabolic Eye"},   // TC_JA
    {439,91,78,32,"Nether Void"},   // TC_JA
    {479,44,95,32,"Scarlet Delirium"},   // TC_JA
    {497,254,96,32,"Soul Enslavement"},   // TC_JA
    {0,88,20,32,"Weapon Bash"},   // TC_JA
    {0,43,87,32,"Arcane Crest"},   // TC_JA
    {0,159,5,19,"Stone"},   // TC_NUKE
    {0,169,11,19,"Water"},   // TC_NUKE
    {0,154,17,19,"Aero"},   // TC_NUKE
    {0,144,23,19,"Fire"},   // TC_NUKE
    {0,149,29,19,"Blizzard"},   // TC_NUKE
    {0,164,35,19,"Thunder"},   // TC_NUKE
    {0,160,42,19,"Stone II"},   // TC_NUKE
    {0,170,48,19,"Water II"},   // TC_NUKE
    {0,155,54,19,"Aero II"},   // TC_NUKE
    {0,145,60,19,"Fire II"},   // TC_NUKE
    {0,150,66,19,"Blizzard II"},   // TC_NUKE
    {0,165,72,19,"Thunder II"},   // TC_NUKE
    {0,161,76,19,"Stone III"},   // TC_NUKE
    {0,171,80,19,"Water III"},   // TC_NUKE
    {0,156,84,19,"Aero III"},   // TC_NUKE
    {0,146,88,19,"Fire III"},   // TC_NUKE
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,151,92,19,"Blizzard III"},   // TC_NUKE
    {0,166,96,19,"Thunder III"},   // TC_NUKE
};
static const JobBuff JT_BST[] = {
    {349,106,75,32,"Killer Instinct"},   // TC_JA
    {498,254,96,32,"Unleash"},   // TC_JA
    {0,97,1,32,"Charm"},   // TC_JA
    {0,0,1,32,"Familiar"},   // TC_JA
    {0,100,1,32,"Fight"},   // TC_JA
    {0,98,10,32,"Gauge"},   // TC_JA
    {0,101,10,32,"Heel"},   // TC_JA
    {0,103,12,32,"Reward"},   // TC_JA
    {0,101,15,32,"Stay"},   // TC_JA
    {0,94,23,32,"Bestial Loyalty"},   // TC_JA
    {0,104,23,32,"Call Beast"},   // TC_JA
    {0,255,25,32,"Ready"},   // TC_JA
    {0,102,25,32,"Sic"},   // TC_JA
    {0,99,30,32,"Tame"},   // TC_JA
    {0,101,35,32,"Leave"},   // TC_JA
    {0,107,45,32,"Snarl"},   // TC_JA
    {0,105,75,32,"Feral Howl"},   // TC_JA
    {0,45,83,32,"Spur"},   // TC_JA
    {0,46,93,32,"Run Wild"},   // TC_JA
};
static const JobBuff JT_BRD[] = {
    {52,0,1,32,"Soul Voice"},   // TC_JA
    {409,112,20,32,"Pianissimo"},   // TC_JA
    {347,109,75,32,"Nightingale"},   // TC_JA
    {348,110,75,32,"Troubadour"},   // TC_JA
    {455,47,83,32,"Tenuto"},   // TC_JA
    {231,48,95,32,"Marcato"},   // TC_JA
    {499,254,96,32,"Clarion Call"},   // TC_JA
    {197,389,1,9,"Knight's Minne"},   // TC_SONG
    {198,394,3,9,"Valor Minuet"},   // TC_SONG
    {195,378,5,9,"Army's Paeon"},   // TC_SONG
    {203,406,9,9,"Herb Pastoral"},   // TC_SONG
    {199,399,11,9,"Sword Madrigal"},   // TC_SONG
    {201,403,13,9,"Sheepfoe Mambo"},   // TC_SONG
    {206,409,19,9,"Scop's Operetta"},   // TC_SONG
    {215,430,22,9,"Enchanting Etude"},   // TC_SONG
    {215,429,24,9,"Spirited Etude"},   // TC_SONG
    {196,386,25,9,"Mage's Ballad"},   // TC_SONG
    {215,428,26,9,"Learned Etude"},   // TC_SONG
    {215,427,28,9,"Quick Etude"},   // TC_SONG
    {214,419,29,9,"Advancing March"},   // TC_SONG
    {215,426,30,9,"Vivacious Etude"},   // TC_SONG
    {200,401,31,9,"Hunter's Prelude"},   // TC_SONG
    {215,425,32,9,"Dextrous Etude"},   // TC_SONG
    {202,405,33,9,"Fowl Aubade"},   // TC_SONG
    {215,424,34,9,"Sinewy Etude"},   // TC_SONG
    {216,444,36,9,"Light Carol"},   // TC_SONG
    {219,467,37,9,"Raptor Mazurka"},   // TC_SONG
    {216,441,38,9,"Earth Carol"},   // TC_SONG
    {216,443,40,9,"Water Carol"},   // TC_SONG
    {216,440,42,9,"Wind Carol"},   // TC_SONG
    {216,438,44,9,"Fire Carol"},   // TC_SONG
    {216,439,46,9,"Ice Carol"},   // TC_SONG
    {216,442,48,9,"Lightning Carol"},   // TC_SONG
    {210,415,49,9,"Goblin Gavotte"},   // TC_SONG
    {216,445,50,9,"Dark Carol"},   // TC_SONG
    {199,400,51,9,"Blade Madrigal"},   // TC_SONG
    {201,404,53,9,"Dragonfoe Mambo"},   // TC_SONG
    {207,412,54,9,"Gold Capriccio"},   // TC_SONG
    {205,408,56,9,"Shining Fantasia"},   // TC_SONG
    {214,420,60,9,"Victory March"},   // TC_SONG
    {215,437,62,9,"Bewitching Etude"},   // TC_SONG
    {215,436,64,9,"Logical Etude"},   // TC_SONG
    {215,435,66,9,"Sage Etude"},   // TC_SONG
    {215,434,68,9,"Swift Etude"},   // TC_SONG
    {206,410,69,9,"Puppet's Operetta"},   // TC_SONG
    {215,433,70,9,"Vital Etude"},   // TC_SONG
    {200,402,71,9,"Archer's Prelude"},   // TC_SONG
    {218,464,71,9,"Goddess's Hymnus"},   // TC_SONG
    {215,432,72,9,"Uncanny Etude"},   // TC_SONG
    {219,465,73,9,"Chocobo Mazurka"},   // TC_SONG
    {209,414,73,9,"Warding Round"},   // TC_SONG
    {215,431,74,9,"Herculean Etude"},   // TC_SONG
    {221,469,75,9,"Adventurer's Dirge"},   // TC_SONG
    {220,468,75,9,"Foe Sirvente"},   // TC_SONG
    {222,470,82,9,"Sentinel's Scherzo"},   // TC_SONG
    {213,418,99,9,"Aria of Passion"},   // TC_SONG
    {214,417,99,9,"Honor March"},   // TC_SONG
    {0,368,7,9,"Foe Requiem"},   // TC_SONG
    {0,460,10,9,"Light Threnody"},   // TC_SONG
    {0,461,12,9,"Dark Threnody"},   // TC_SONG
    {0,457,14,9,"Earth Threnody"},   // TC_SONG
    {0,463,16,9,"Foe Lullaby"},   // TC_SONG
    {0,459,16,9,"Water Threnody"},   // TC_SONG
    {0,369,17,9,"Foe Requiem II"},   // TC_SONG
    {0,456,18,9,"Wind Threnody"},   // TC_SONG
    {0,454,20,9,"Fire Threnody"},   // TC_SONG
    {0,455,22,9,"Ice Threnody"},   // TC_SONG
    {0,458,24,9,"Ltng. Threnody"},   // TC_SONG
    {0,376,27,9,"Horde Lullaby"},   // TC_SONG
    {0,462,33,9,"Magic Finale"},   // TC_SONG
    {0,370,37,9,"Foe Requiem III"},   // TC_SONG
    {0,421,39,9,"Battlefield Elegy"},   // TC_SONG
    {0,371,47,9,"Foe Requiem IV"},   // TC_SONG
    {0,372,57,9,"Foe Requiem V"},   // TC_SONG
    {0,422,59,9,"Carnage Elegy"},   // TC_SONG
    {0,373,67,9,"Foe Requiem VI"},   // TC_SONG
    {0,466,75,9,"Maiden's Virelai"},   // TC_SONG
    {0,374,76,9,"Foe Requiem VII"},   // TC_SONG
    {0,471,83,9,"Foe Lullaby II"},   // TC_SONG
    {0,377,92,9,"Horde Lullaby II"},   // TC_SONG
    {0,472,95,9,"Pining Nocturne"},   // TC_SONG
    {0,878,100,9,"Dark Threnody II"},   // TC_SONG
    {0,874,100,9,"Earth Threnody II"},   // TC_SONG
    {0,871,100,9,"Fire Threnody II"},   // TC_SONG
    {0,872,100,9,"Ice Threnody II"},   // TC_SONG
    {0,877,100,9,"Light Threnody II"},   // TC_SONG
    {0,875,100,9,"Ltng. Threnody II"},   // TC_SONG
    {0,876,100,9,"Water Threnody II"},   // TC_SONG
    {0,873,100,9,"Wind Threnody II"},   // TC_SONG
};
static const JobBuff JT_RNG[] = {
    {72,124,1,32,"Sharpshot"},   // TC_JA
    {73,125,30,32,"Barrage"},   // TC_JA
    {371,129,45,32,"Velocity Shot"},   // TC_JA
    {115,126,51,32,"Unlimited Shot"},   // TC_JA
    {351,128,75,32,"Flashy Shot"},   // TC_JA
    {350,127,75,32,"Stealth Shot"},   // TC_JA
    {433,126,79,32,"Double Shot"},   // TC_JA
    {482,52,95,32,"Decoy Shot"},   // TC_JA
    {500,254,96,32,"Overkill"},   // TC_JA
    {0,0,1,32,"Eagle Eye Shot"},   // TC_JA
    {0,121,10,32,"Scavenge"},   // TC_JA
    {0,123,20,32,"Camouflage"},   // TC_JA
    {0,122,40,32,"Shadowbind"},   // TC_JA
    {0,51,87,32,"Bounty Shot"},   // TC_JA
    {0,151,95,32,"Hover Shot"},   // TC_JA
};
static const JobBuff JT_SAM[] = {
    {54,0,1,32,"Meikyo Shisui"},   // TC_JA
    {117,135,5,32,"Warding Circle"},   // TC_JA
    {67,133,15,32,"Third Eye"},   // TC_JA
    {353,138,25,32,"Hasso"},   // TC_JA
    {354,139,35,32,"Seigan"},   // TC_JA
    {440,141,77,32,"Sengikori"},   // TC_JA
    {483,54,95,32,"Hagakure"},   // TC_JA
    {501,254,96,32,"Yaegasumi"},   // TC_JA
    {0,134,30,32,"Meditate"},   // TC_JA
    {0,140,40,32,"Sekkanoki"},   // TC_JA
    {0,132,65,32,"Konzen-ittai"},   // TC_JA
    {0,137,75,32,"Blade Bash"},   // TC_JA
    {0,136,75,32,"Shikikoyo"},   // TC_JA
    {0,53,87,32,"Hamanoha"},   // TC_JA
};
static const JobBuff JT_NIN[] = {
    {421,147,40,32,"Innin"},   // TC_JA
    {420,146,40,32,"Yonin"},   // TC_JA
    {352,145,75,32,"Sange"},   // TC_JA
    {441,148,77,32,"Futae"},   // TC_JA
    {484,57,95,32,"Issekigan"},   // TC_JA
    {502,254,96,32,"Mikage"},   // TC_JA
    {0,0,1,32,"Mijin Gakure"},   // TC_JA
    {69,353,9,11,"Tonko: Ichi"},   // TC_NINJUTSU
    {71,318,25,11,"Monomi: Ichi"},   // TC_NINJUTSU
    {69,354,34,11,"Tonko: Ni"},   // TC_NINJUTSU
    {290,507,85,11,"Myoshu: Ichi"},   // TC_NINJUTSU
    {289,505,88,11,"Gekka: Ichi"},   // TC_NINJUTSU
    {471,510,88,11,"Migawari: Ichi"},   // TC_NINJUTSU
    {171,506,91,11,"Yain: Ichi"},   // TC_NINJUTSU
    {227,509,93,11,"Kakka: Ichi"},   // TC_NINJUTSU
    {0,338,12,11,"Utsusemi: Ichi"},   // TC_NINJUTSU
    {0,329,15,11,"Doton: Ichi"},   // TC_NINJUTSU
    {0,326,15,11,"Huton: Ichi"},   // TC_NINJUTSU
    {0,323,15,11,"Hyoton: Ichi"},   // TC_NINJUTSU
    {0,320,15,11,"Katon: Ichi"},   // TC_NINJUTSU
    {0,332,15,11,"Raiton: Ichi"},   // TC_NINJUTSU
    {0,335,15,11,"Suiton: Ichi"},   // TC_NINJUTSU
    {0,347,19,11,"Kurayami: Ichi"},   // TC_NINJUTSU
    {0,344,23,11,"Hojo: Ichi"},   // TC_NINJUTSU
    {0,350,27,11,"Dokumori: Ichi"},   // TC_NINJUTSU
    {0,341,30,11,"Jubaku: Ichi"},   // TC_NINJUTSU
    {0,339,37,11,"Utsusemi: Ni"},   // TC_NINJUTSU
    {0,330,40,11,"Doton: Ni"},   // TC_NINJUTSU
    {0,327,40,11,"Huton: Ni"},   // TC_NINJUTSU
    {0,324,40,11,"Hyoton: Ni"},   // TC_NINJUTSU
    {0,321,40,11,"Katon: Ni"},   // TC_NINJUTSU
    {0,333,40,11,"Raiton: Ni"},   // TC_NINJUTSU
    {0,336,40,11,"Suiton: Ni"},   // TC_NINJUTSU
    {0,348,44,11,"Kurayami: Ni"},   // TC_NINJUTSU
    {0,345,48,11,"Hojo: Ni"},   // TC_NINJUTSU
    {0,331,75,11,"Doton: San"},   // TC_NINJUTSU
    {0,328,75,11,"Huton: San"},   // TC_NINJUTSU
    {0,325,75,11,"Hyoton: San"},   // TC_NINJUTSU
    {0,322,75,11,"Katon: San"},   // TC_NINJUTSU
    {0,334,75,11,"Raiton: San"},   // TC_NINJUTSU
    {0,337,75,11,"Suiton: San"},   // TC_NINJUTSU
    {0,319,78,11,"Aisha: Ichi"},   // TC_NINJUTSU
    {0,508,83,11,"Yurin: Ichi"},   // TC_NINJUTSU
    {0,340,100,11,"Utsusemi: San"},   // TC_NINJUTSU
};
static const JobBuff JT_DRG[] = {
    {126,0,1,32,"Spirit Surge"},   // TC_JA
    {118,157,5,32,"Ancient Circle"},   // TC_JA
    {503,254,96,32,"Fly High"},   // TC_JA
    {0,163,1,32,"Call Wyvern"},   // TC_JA
    {0,161,1,32,"Dismiss"},   // TC_JA
    {0,158,10,32,"Jump"},   // TC_JA
    {0,162,25,32,"Spirit Link"},   // TC_JA
    {0,159,35,32,"High Jump"},   // TC_JA
    {0,160,50,32,"Super Jump"},   // TC_JA
    {0,149,65,32,"Spirit Bond"},   // TC_JA
    {0,165,75,32,"Angon"},   // TC_JA
    {0,164,75,32,"Deep Breathing"},   // TC_JA
    {0,166,77,32,"Spirit Jump"},   // TC_JA
    {0,167,85,32,"Soul Jump"},   // TC_JA
    {0,58,87,32,"Dragon Breaker"},   // TC_JA
    {0,239,90,32,"Restoring Breath"},   // TC_JA
    {0,238,90,32,"Smiting Breath"},   // TC_JA
    {0,70,95,32,"Steady Wing"},   // TC_JA
};
static const JobBuff JT_SMN[] = {
    {36,174,1,31,"Aerial Armor"},   // TC_BPACT
    {113,174,1,31,"Altana's Favor"},   // TC_BPACT
    {39,174,1,31,"Chinook"},   // TC_BPACT
    {68,174,1,31,"Crimson Howl"},   // TC_BPACT
    {587,174,1,31,"Crystal Blessing"},   // TC_BPACT
    {190,174,1,31,"Dream Shroud"},   // TC_BPACT
    {458,174,1,31,"Earthen Armor"},   // TC_BPACT
    {37,174,1,31,"Earthen Ward"},   // TC_BPACT
    {176,174,1,31,"Fleet Wind"},   // TC_BPACT
    {35,174,1,31,"Frost Armor"},   // TC_BPACT
    {33,174,1,31,"Hastega"},   // TC_BPACT
    {33,174,1,31,"Hastega II"},   // TC_BPACT
    {94,174,1,31,"Inferno Howl"},   // TC_BPACT
    {96,174,1,31,"Katabatic Blades"},   // TC_BPACT
    {38,174,1,31,"Lightning Armor"},   // TC_BPACT
    {116,174,1,31,"Noctoshield"},   // TC_BPACT
    {113,174,1,31,"Reraise II"},   // TC_BPACT
    {98,174,1,31,"Rolling Thunder"},   // TC_BPACT
    {154,174,1,31,"Shining Ruby"},   // TC_BPACT
    {586,174,1,31,"Soothing Current"},   // TC_BPACT
    {152,174,1,31,"Wind's Blessing"},   // TC_BPACT
    {0,174,1,31,"Bitter Elegy"},   // TC_BPACT
    {0,174,1,31,"Diamond Storm"},   // TC_BPACT
    {0,174,1,31,"Ecliptic Growl"},   // TC_BPACT
    {0,174,1,31,"Ecliptic Howl"},   // TC_BPACT
    {0,174,1,31,"Eerie Eye"},   // TC_BPACT
    {0,174,1,31,"Glittering Ruby"},   // TC_BPACT
    {0,174,1,31,"Healing Ruby"},   // TC_BPACT
    {0,174,1,31,"Healing Ruby II"},   // TC_BPACT
    {0,174,1,31,"Heavenward Howl"},   // TC_BPACT
    {0,174,1,31,"Lunar Cry"},   // TC_BPACT
    {0,174,1,31,"Lunar Roar"},   // TC_BPACT
    {0,174,1,31,"Lunatic Voice"},   // TC_BPACT
    {0,174,1,31,"Mewing Lullaby"},   // TC_BPACT
    {0,174,1,31,"Nightmare"},   // TC_BPACT
    {0,174,1,31,"Pacifying Ruby"},   // TC_BPACT
    {0,174,1,31,"Pavor Nocturnus"},   // TC_BPACT
    {0,174,1,31,"Raise II"},   // TC_BPACT
    {0,174,1,31,"Shock Squall"},   // TC_BPACT
    {0,174,1,31,"Sleepga"},   // TC_BPACT
    {0,174,1,31,"Slowga"},   // TC_BPACT
    {0,174,1,31,"Somnolence"},   // TC_BPACT
    {0,174,1,31,"Soothing Ruby"},   // TC_BPACT
    {0,174,1,31,"Spring Water"},   // TC_BPACT
    {0,174,1,31,"Tidal Roar"},   // TC_BPACT
    {0,174,1,31,"Ultimate Terror"},   // TC_BPACT
    {0,174,1,31,"Whispering Wind"},   // TC_BPACT
    {583,108,1,32,"Apogee"},   // TC_JA
    {504,254,1,32,"Astral Conduit"},   // TC_JA
    {55,0,1,32,"Astral Flow"},   // TC_JA
    {0,71,1,32,"Mana Cede"},   // TC_JA
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,290,1,23,"Air Spirit"},   // TC_SUMMON
    {0,307,1,23,"Cait Sith"},   // TC_SUMMON
    {0,296,1,23,"Carbuncle"},   // TC_SUMMON
    {0,295,1,23,"Dark Spirit"},   // TC_SUMMON
    {0,304,1,23,"Diabolos"},   // TC_SUMMON
    {0,291,1,23,"Earth Spirit"},   // TC_SUMMON
    {0,297,1,23,"Fenrir"},   // TC_SUMMON
    {0,288,1,23,"Fire Spirit"},   // TC_SUMMON
    {0,301,1,23,"Garuda"},   // TC_SUMMON
    {0,289,1,23,"Ice Spirit"},   // TC_SUMMON
    {0,298,1,23,"Ifrit"},   // TC_SUMMON
    {0,300,1,23,"Leviathan"},   // TC_SUMMON
    {0,294,1,23,"Light Spirit"},   // TC_SUMMON
    {0,303,1,23,"Ramuh"},   // TC_SUMMON
    {0,302,1,23,"Shiva"},   // TC_SUMMON
    {0,355,1,23,"Siren"},   // TC_SUMMON
    {0,292,1,23,"Thunder Spirit"},   // TC_SUMMON
    {0,299,1,23,"Titan"},   // TC_SUMMON
    {0,293,1,23,"Water Spirit"},   // TC_SUMMON
    {0,306,75,23,"Alexander"},   // TC_SUMMON
    {0,847,75,23,"Atomos"},   // TC_SUMMON
    {0,305,75,23,"Odin"},   // TC_SUMMON
};
static const JobBuff JT_BLU[] = {
    {93,547,8,13,"Cocoon"},   // TC_BLU_BUFF
    {37,517,8,13,"Metallic Body"},   // TC_BLU_BUFF
    {33,530,48,13,"Refueling"},   // TC_BLU_BUFF
    {92,574,56,13,"Feather Barrier"},   // TC_BLU_BUFF
    {190,538,62,13,"Memento Mori"},   // TC_BLU_BUFF
    {36,647,65,13,"Zephyr Mantle"},   // TC_BLU_BUFF
    {37,632,67,13,"Diamondhide"},   // TC_BLU_BUFF
    {91,655,71,13,"Triumphant Roar"},   // TC_BLU_BUFF
    {191,614,72,13,"Saline Coat"},   // TC_BLU_BUFF
    {93,613,74,13,"Reactor Cool"},   // TC_BLU_BUFF
    {38,615,75,13,"Plasma Charge"},   // TC_BLU_BUFF
    {42,664,78,13,"Regeneration"},   // TC_BLU_BUFF
    {33,661,79,13,"Animating Wail"},   // TC_BLU_BUFF
    {43,662,79,13,"Battery Charge"},   // TC_BLU_BUFF
    {152,668,82,13,"Magic Barrier"},   // TC_BLU_BUFF
    {45,674,85,13,"Fantod"},   // TC_BLU_BUFF
    {36,679,88,13,"Occultation"},   // TC_BLU_BUFF
    {116,685,91,13,"Barrier Tusk"},   // TC_BLU_BUFF
    {93,737,95,13,"Harden Shell"},   // TC_BLU_BUFF
    {486,696,98,13,"O. Counterstance"},   // TC_BLU_BUFF
    {150,741,98,13,"Pyric Bulwark"},   // TC_BLU_BUFF
    {91,745,99,13,"Carcharian Verve"},   // TC_BLU_BUFF
    {33,710,99,13,"Erratic Flutter"},   // TC_BLU_BUFF
    {604,750,99,13,"Mighty Guard"},   // TC_BLU_BUFF
    {91,700,99,13,"Nat. Meditation"},   // TC_BLU_BUFF
    {0,549,1,16,"Pollen"},   // TC_BLU_DEB
    {0,581,16,16,"Healing Breeze"},   // TC_BLU_DEB
    {0,584,16,16,"Sheep Song"},   // TC_BLU_DEB
    {0,544,18,16,"Cursed Sphere"},   // TC_BLU_DEB
    {0,598,24,16,"Soporific"},   // TC_BLU_DEB
    {0,578,30,16,"Wild Carrot"},   // TC_BLU_DEB
    {0,582,32,16,"Chaotic Eye"},   // TC_BLU_DEB
    {0,572,32,16,"Sound Blast"},   // TC_BLU_DEB
    {0,592,38,16,"Blank Gaze"},   // TC_BLU_DEB
    {0,521,42,16,"MP Drainkiss"},   // TC_BLU_DEB
    {0,513,42,16,"Venom Shell"},   // TC_BLU_DEB
    {0,537,44,16,"Stinking Gas"},   // TC_BLU_DEB
    {0,606,46,16,"Awful Eye"},   // TC_BLU_DEB
    {0,605,46,16,"Geist Wall"},   // TC_BLU_DEB
    {0,575,48,16,"Jettatura"},   // TC_BLU_DEB
    {0,561,50,16,"Frightful Roar"},   // TC_BLU_DEB
    {0,535,52,16,"Cold Wave"},   // TC_BLU_DEB
    {0,548,52,16,"Filamented Hold"},   // TC_BLU_DEB
    {0,634,58,16,"Light of Penance"},   // TC_BLU_DEB
    {0,593,58,16,"Magic Fruit"},   // TC_BLU_DEB
    {0,604,61,16,"Bad Breath"},   // TC_BLU_DEB
    {0,579,64,16,"Voracious Trunk"},   // TC_BLU_DEB
    {0,576,64,16,"Yawn"},   // TC_BLU_DEB
    {0,610,65,16,"Infrasonics"},   // TC_BLU_DEB
    {0,621,66,16,"Sandspray"},   // TC_BLU_DEB
    {0,633,67,16,"Enervation"},   // TC_BLU_DEB
    {0,636,68,16,"Warm-Up"},   // TC_BLU_DEB
    {0,642,70,16,"Amplification"},   // TC_BLU_DEB
    {0,588,71,16,"Lowing"},   // TC_BLU_DEB
    {0,616,73,16,"Temporal Shift"},   // TC_BLU_DEB
    {0,612,74,16,"Actinic Burst"},   // TC_BLU_DEB
    {0,645,75,16,"Exuviation"},   // TC_BLU_DEB
    {0,658,76,16,"Plenilune Embrace"},   // TC_BLU_DEB
    {0,660,78,16,"Cimicine Discharge"},   // TC_BLU_DEB
    {0,659,80,16,"Demoralizing Roar"},   // TC_BLU_DEB
    {0,671,84,16,"Auroral Drape"},   // TC_BLU_DEB
    {0,678,87,16,"Dream Flower"},   // TC_BLU_DEB
    {0,681,89,16,"Winds of Promy."},   // TC_BLU_DEB
    {0,684,90,16,"Reaving Wind"},   // TC_BLU_DEB
    {0,686,91,16,"Mortal Ray"},   // TC_BLU_DEB
    {0,690,94,16,"White Wind"},   // TC_BLU_DEB
    {0,736,95,16,"Thunderbolt"},   // TC_BLU_DEB
    {0,738,96,16,"Absolute Terror"},   // TC_BLU_DEB
    {0,739,97,16,"Gates of Hades"},   // TC_BLU_DEB
    {0,740,97,16,"Tourbillion"},   // TC_BLU_DEB
    {0,742,99,16,"Bilgestorm"},   // TC_BLU_DEB
    {0,746,99,16,"Blistering Roar"},   // TC_BLU_DEB
    {0,743,99,16,"Bloodrake"},   // TC_BLU_DEB
    {0,752,99,16,"Cesspool"},   // TC_BLU_DEB
    {0,748,99,16,"Crashing Thunder"},   // TC_BLU_DEB
    {0,751,99,16,"Cruel Joke"},   // TC_BLU_DEB
    {0,744,99,16,"Droning Whirlwind"},   // TC_BLU_DEB
    {0,749,99,16,"Polar Roar"},   // TC_BLU_DEB
    {0,711,99,16,"Restoral"},   // TC_BLU_DEB
    {0,753,99,16,"Tearing Gust"},   // TC_BLU_DEB
    {0,747,99,16,"Uproot"},   // TC_BLU_DEB
    {0,524,1,15,"Sandspin"},   // TC_BLU_MAG
    {0,618,18,15,"Blastbomb"},   // TC_BLU_MAG
    {0,570,20,15,"Blood Drain"},   // TC_BLU_MAG
    {0,536,22,15,"Poison Breath"},   // TC_BLU_MAG
    {0,626,28,15,"Bomb Toss"},   // TC_BLU_MAG
    {0,522,34,15,"Death Ray"},   // TC_BLU_MAG
    {0,542,36,15,"Digest"},   // TC_BLU_MAG
    {0,534,40,15,"Mysterious Light"},   // TC_BLU_MAG
    {0,532,44,15,"Blitzstrahl"},   // TC_BLU_MAG
    {0,555,46,15,"Magnetite Cloud"},   // TC_BLU_MAG
    {0,541,48,15,"Blood Saber"},   // TC_BLU_MAG
    {0,531,50,15,"Ice Break"},   // TC_BLU_MAG
    {0,533,50,15,"Self-Destruct"},   // TC_BLU_MAG
    {0,563,54,15,"Hecatomb Wave"},   // TC_BLU_MAG
    {0,565,54,15,"Radiant Breath"},   // TC_BLU_MAG
    {0,629,58,15,"Flying Hip Press"},   // TC_BLU_MAG
    {0,557,61,15,"Eyes On Me"},   // TC_BLU_MAG
    {0,515,61,15,"Maelstrom"},   // TC_BLU_MAG
    {0,595,62,15,"1000 Needles"},   // TC_BLU_MAG
    {0,651,66,15,"Corrosive Ooze"},   // TC_BLU_MAG
    {0,608,66,15,"Frost Breath"},   // TC_BLU_MAG
    {0,637,68,15,"Firespit"},   // TC_BLU_MAG
    {0,648,69,15,"Regurgitation"},   // TC_BLU_MAG
    {0,591,71,15,"Heat Breath"},   // TC_BLU_MAG
    {0,644,73,15,"Mind Blast"},   // TC_BLU_MAG
    {0,646,74,15,"Magic Hammer"},   // TC_BLU_MAG
    {0,656,77,15,"Acrid Stream"},   // TC_BLU_MAG
    {0,663,77,15,"Leafstorm"},   // TC_BLU_MAG
    {0,657,80,15,"Blazing Bound"},   // TC_BLU_MAG
    {0,672,84,15,"Osmosis"},   // TC_BLU_MAG
    {0,675,86,15,"Thermal Pulse"},   // TC_BLU_MAG
    {0,680,88,15,"Charged Whisker"},   // TC_BLU_MAG
    {0,683,90,15,"Evryone. Grudge"},   // TC_BLU_MAG
    {0,687,92,15,"Water Bomb"},   // TC_BLU_MAG
    {0,689,93,15,"Dark Orb"},   // TC_BLU_MAG
    {0,694,96,15,"Vapor Spray"},   // TC_BLU_MAG
    {0,695,97,15,"Thunder Breath"},   // TC_BLU_MAG
    {0,721,99,15,"Anvil Lightning"},   // TC_BLU_MAG
    {0,718,99,15,"Atra. Libations"},   // TC_BLU_MAG
    {0,725,99,15,"Blinding Fulgor"},   // TC_BLU_MAG
    {0,713,99,15,"Diffusion Ray"},   // TC_BLU_MAG
    {0,703,99,15,"Embalming Earth"},   // TC_BLU_MAG
    {0,722,99,15,"Entomb"},   // TC_BLU_MAG
    {0,705,99,15,"Foul Waters"},   // TC_BLU_MAG
    {0,715,99,15,"Molting Plumage"},   // TC_BLU_MAG
    {0,716,99,15,"Nectarous Deluge"},   // TC_BLU_MAG
    {0,724,99,15,"Palling Salvo"},   // TC_BLU_MAG
    {0,712,99,15,"Rail Cannon"},   // TC_BLU_MAG
    {0,702,99,15,"Rending Deluge"},   // TC_BLU_MAG
    {0,707,99,15,"Retinal Glare"},   // TC_BLU_MAG
    {0,726,99,15,"Scouring Spate"},   // TC_BLU_MAG
    {0,719,99,15,"Searing Tempest"},   // TC_BLU_MAG
    {0,727,99,15,"Silent Storm"},   // TC_BLU_MAG
    {0,720,99,15,"Spectral Floe"},   // TC_BLU_MAG
    {0,708,99,15,"Subduction"},   // TC_BLU_MAG
    {0,701,99,15,"Tem. Upheaval"},   // TC_BLU_MAG
    {0,728,99,15,"Tenebral Crush"},   // TC_BLU_MAG
    {0,698,99,15,"Wind Breath"},   // TC_BLU_MAG
    {0,577,1,14,"Foot Kick"},   // TC_BLU_PHYS
    {0,551,4,14,"Power Attack"},   // TC_BLU_PHYS
    {0,597,4,14,"Sprout Smack"},   // TC_BLU_PHYS
    {0,603,4,14,"Wild Oats"},   // TC_BLU_PHYS
    {0,599,8,14,"Queasyshroom"},   // TC_BLU_PHYS
    {0,620,12,14,"Battle Dance"},   // TC_BLU_PHYS
    {0,638,12,14,"Feather Storm"},   // TC_BLU_PHYS
    {0,623,12,14,"Head Butt"},   // TC_BLU_PHYS
    {0,567,16,14,"Helldive"},   // TC_BLU_PHYS
    {0,529,18,14,"Bludgeon"},   // TC_BLU_PHYS
    {0,587,20,14,"Claw Cyclone"},   // TC_BLU_PHYS
    {0,519,26,14,"Screwdriver"},   // TC_BLU_PHYS
    {0,622,30,14,"Grand Slam"},   // TC_BLU_PHYS
    {0,527,34,14,"Smite of Rage"},   // TC_BLU_PHYS
    {0,596,36,14,"Pinecone Bomb"},   // TC_BLU_PHYS
    {0,569,38,14,"Jet Stream"},   // TC_BLU_PHYS
    {0,594,38,14,"Uppercut"},   // TC_BLU_PHYS
    {0,539,40,14,"Terror Touch"},   // TC_BLU_PHYS
    {0,543,44,14,"Mandibular Bite"},   // TC_BLU_PHYS
    {0,545,48,14,"Sickle Slash"},   // TC_BLU_PHYS
    {0,554,60,14,"Death Scissors"},   // TC_BLU_PHYS
    {0,589,60,14,"Dimensional Death"},   // TC_BLU_PHYS
    {0,652,60,14,"Spiral Spin"},   // TC_BLU_PHYS
    {0,650,61,14,"Seedspray"},   // TC_BLU_PHYS
    {0,564,62,14,"Body Slam"},   // TC_BLU_PHYS
    {0,560,63,14,"Frenetic Rip"},   // TC_BLU_PHYS
    {0,628,63,14,"Frypan"},   // TC_BLU_PHYS
    {0,631,63,14,"Hydro Shot"},   // TC_BLU_PHYS
    {0,540,63,14,"Spinal Cleave"},   // TC_BLU_PHYS
    {0,573,64,14,"Feather Tickle"},   // TC_BLU_PHYS
    {0,641,69,14,"Hysteric Barrage"},   // TC_BLU_PHYS
    {0,640,69,14,"Tail Slap"},   // TC_BLU_PHYS
    {0,653,70,14,"Asuran Claws"},   // TC_BLU_PHYS
    {0,643,70,14,"Cannonball"},   // TC_BLU_PHYS
    {0,611,72,14,"Disseverment"},   // TC_BLU_PHYS
    {0,654,72,14,"Sub-zero Smash"},   // TC_BLU_PHYS
    {0,585,73,14,"Ram Charge"},   // TC_BLU_PHYS
    {0,617,75,14,"Vertical Cleave"},   // TC_BLU_PHYS
    {0,665,81,14,"Final Sting"},   // TC_BLU_PHYS
    {0,666,81,14,"Goblin Rush"},   // TC_BLU_PHYS
    {0,667,82,14,"Vanity Dive"},   // TC_BLU_PHYS
    {0,670,83,14,"Benthic Typhoon"},   // TC_BLU_PHYS
    {0,669,83,14,"Whirl of Rage"},   // TC_BLU_PHYS
    {0,673,85,14,"Quad. Continuum"},   // TC_BLU_PHYS
    {0,677,87,14,"Empty Thrash"},   // TC_BLU_PHYS
    {0,682,89,14,"Delta Thrust"},   // TC_BLU_PHYS
    {0,688,92,14,"Heavy Strike"},   // TC_BLU_PHYS
    {0,692,95,14,"Sudden Lunge"},   // TC_BLU_PHYS
    {0,693,96,14,"Quadrastrike"},   // TC_BLU_PHYS
    {0,697,98,14,"Amorphic Spikes"},   // TC_BLU_PHYS
    {0,699,99,14,"Barbed Crescent"},   // TC_BLU_PHYS
    {0,706,99,14,"Glutinous Dart"},   // TC_BLU_PHYS
    {0,704,99,14,"Paralyzing Triad"},   // TC_BLU_PHYS
    {0,723,99,14,"Saurian Slide"},   // TC_BLU_PHYS
    {0,714,99,14,"Sinker Drill"},   // TC_BLU_PHYS
    {0,717,99,14,"Sweeping Gouge"},   // TC_BLU_PHYS
    {0,709,99,14,"Thrashing Assault"},   // TC_BLU_PHYS
    {163,0,1,32,"Azure Lore"},   // TC_JA
    {165,182,25,32,"Burst Affinity"},   // TC_JA
    {164,181,40,32,"Chain Affinity"},   // TC_JA
    {355,183,75,32,"Convergence"},   // TC_JA
    {356,184,75,32,"Diffusion"},   // TC_JA
    {457,185,83,32,"Efflux"},   // TC_JA
    {485,81,95,32,"Unbridled Learning"},   // TC_JA
    {505,254,96,32,"Unbridled Wisdom"},   // TC_JA
};
static const JobBuff JT_COR[] = {
    {357,197,75,32,"Snake Eye"},   // TC_JA
    {467,84,87,32,"Triple Shot"},   // TC_JA
    {601,96,95,32,"Crooked Cards"},   // TC_JA
    {0,0,1,32,"Wild Card"},   // TC_JA
    {0,194,5,32,"Double-Up"},   // TC_JA
    {0,199,40,32,"Quick Draw"},   // TC_JA
    {0,196,50,32,"Random Deal"},   // TC_JA
    {0,198,75,32,"Fold"},   // TC_JA
    {0,254,96,32,"Cutting Cards"},   // TC_JA
    {326,193,5,25,"Corsair's Roll"},   // TC_ROLL
    {322,193,8,25,"Ninja Roll"},   // TC_ROLL
    {320,193,11,25,"Hunter's Roll"},   // TC_ROLL
    {317,193,14,25,"Chaos Roll"},   // TC_ROLL
    {325,193,17,25,"Magus's Roll"},   // TC_ROLL
    {312,193,20,25,"Healer's Roll"},   // TC_ROLL
    {323,193,23,25,"Drachen Roll"},   // TC_ROLL
    {319,193,26,25,"Choral Roll"},   // TC_ROLL
    {311,193,31,25,"Monk's Roll"},   // TC_ROLL
    {318,193,34,25,"Beast Roll"},   // TC_ROLL
    {321,193,37,25,"Samurai Roll"},   // TC_ROLL
    {324,193,40,25,"Evoker's Roll"},   // TC_ROLL
    {315,193,43,25,"Rogue's Roll"},   // TC_ROLL
    {314,193,46,25,"Warlock's Roll"},   // TC_ROLL
    {310,193,49,25,"Fighter's Roll"},   // TC_ROLL
    {327,193,52,25,"Puppet Roll"},   // TC_ROLL
    {316,193,55,25,"Gallant's Roll"},   // TC_ROLL
    {313,193,58,25,"Wizard's Roll"},   // TC_ROLL
    {328,193,61,25,"Dancer's Roll"},   // TC_ROLL
    {329,193,64,25,"Scholar's Roll"},   // TC_ROLL
    {339,193,67,25,"Naturalist's Roll"},   // TC_ROLL
    {600,193,70,25,"Runeist's Roll"},   // TC_ROLL
    {330,193,76,25,"Bolter's Roll"},   // TC_ROLL
    {331,193,79,25,"Caster's Roll"},   // TC_ROLL
    {332,193,81,25,"Courser's Roll"},   // TC_ROLL
    {333,193,83,25,"Blitzer's Roll"},   // TC_ROLL
    {334,193,86,25,"Tactician's Roll"},   // TC_ROLL
    {335,193,89,25,"Allies' Roll"},   // TC_ROLL
    {336,193,92,25,"Miser's Roll"},   // TC_ROLL
    {337,193,95,25,"Companion's Roll"},   // TC_ROLL
    {338,193,97,25,"Avenger's Roll"},   // TC_ROLL
};
static const JobBuff JT_PUP[] = {
    {166,0,1,32,"Overdrive"},   // TC_JA
    {0,205,1,32,"Activate"},   // TC_JA
    {0,210,1,32,"Dark Maneuver"},   // TC_JA
    {0,208,1,32,"Deactivate"},   // TC_JA
    {0,207,1,32,"Deploy"},   // TC_JA
    {0,210,1,32,"Earth Maneuver"},   // TC_JA
    {0,210,1,32,"Fire Maneuver"},   // TC_JA
    {0,210,1,32,"Ice Maneuver"},   // TC_JA
    {0,210,1,32,"Light Maneuver"},   // TC_JA
    {0,210,1,32,"Thunder Maneuver"},   // TC_JA
    {0,210,1,32,"Water Maneuver"},   // TC_JA
    {0,210,1,32,"Wind Maneuver"},   // TC_JA
    {0,115,5,32,"Deus Ex Automata"},   // TC_JA
    {0,209,10,32,"Retrieve"},   // TC_JA
    {0,206,15,32,"Repair"},   // TC_JA
    {0,214,30,32,"Maintenance"},   // TC_JA
    {0,211,75,32,"Role Reversal"},   // TC_JA
    {0,212,75,32,"Ventriloquy"},   // TC_JA
    {0,213,79,32,"Tactical Switch"},   // TC_JA
    {0,114,95,32,"Cooldown"},   // TC_JA
    {0,254,96,32,"Heady Artifice"},   // TC_JA
};
static const JobBuff JT_DNC[] = {
    {375,222,50,27,"Building Flourish"},   // TC_DANCE
    {176,218,55,27,"Chocobo Jig"},   // TC_DANCE
    {176,218,70,27,"Chocobo Jig II"},   // TC_DANCE
    {443,226,80,27,"Climactic Flourish"},   // TC_DANCE
    {468,226,89,27,"Striking Flourish"},   // TC_DANCE
    {472,226,93,27,"Ternary Flourish"},   // TC_DANCE
    {0,217,15,27,"Curing Waltz"},   // TC_DANCE
    {0,221,20,27,"Animated Flourish"},   // TC_DANCE
    {0,220,20,27,"Quickstep"},   // TC_DANCE
    {0,225,25,27,"Divine Waltz"},   // TC_DANCE
    {0,218,25,27,"Spectral Jig"},   // TC_DANCE
    {0,220,30,27,"Box Step"},   // TC_DANCE
    {0,186,30,27,"Curing Waltz II"},   // TC_DANCE
    {0,221,30,27,"Desperate Flourish"},   // TC_DANCE
    {0,215,35,27,"Healing Waltz"},   // TC_DANCE
    {0,222,40,27,"Reverse Flourish"},   // TC_DANCE
    {0,220,40,27,"Stutter Step"},   // TC_DANCE
    {0,187,45,27,"Curing Waltz III"},   // TC_DANCE
    {0,221,45,27,"Violent Flourish"},   // TC_DANCE
    {0,222,60,27,"Wild Flourish"},   // TC_DANCE
    {0,188,70,27,"Curing Waltz IV"},   // TC_DANCE
    {0,190,78,27,"Divine Waltz II"},   // TC_DANCE
    {0,220,83,27,"Feather Step"},   // TC_DANCE
    {0,189,87,27,"Curing Waltz V"},   // TC_DANCE
    {376,0,1,32,"Trance"},   // TC_JA
    {582,229,50,32,"Contradance"},   // TC_JA
    {411,224,75,32,"Fan Dance"},   // TC_JA
    {410,219,75,32,"Saber Dance"},   // TC_JA
    {442,236,77,32,"Presto"},   // TC_JA
    {507,254,96,32,"Grand Pas"},   // TC_JA
    {0,223,75,32,"No Foot Rise"},   // TC_JA
    {368,216,5,26,"Drain Samba"},   // TC_SAMBA
    {369,216,25,26,"Aspir Samba"},   // TC_SAMBA
    {368,216,35,26,"Drain Samba II"},   // TC_SAMBA
    {370,216,45,26,"Haste Samba"},   // TC_SAMBA
    {369,216,60,26,"Aspir Samba II"},   // TC_SAMBA
    {368,216,65,26,"Drain Samba III"},   // TC_SAMBA
};
static const JobBuff JT_SCH[] = {
    {407,287,46,21,"Klimaform"},   // TC_DARK
    {0,502,5,21,"Kaustra"},   // TC_DARK
    {0,245,21,21,"Drain"},   // TC_DARK
    {0,247,36,21,"Aspir"},   // TC_DARK
    {0,248,97,21,"Aspir II"},   // TC_DARK
    {39,55,13,8,"Aquaveil"},   // TC_DEFENSE
    {36,53,29,8,"Blink"},   // TC_DEFENSE
    {37,54,44,8,"Stoneskin"},   // TC_DEFENSE
    {0,253,30,20,"Sleep"},   // TC_ENFEEBLE
    {0,260,32,20,"Dispel"},   // TC_ENFEEBLE
    {0,259,65,20,"Sleep II"},   // TC_ENFEEBLE
    {0,255,90,20,"Break"},   // TC_ENFEEBLE
    {228,478,5,17,"Embrava"},   // TC_ENHANCE
    {70,138,15,17,"Deodorize"},   // TC_ENHANCE
    {71,137,20,17,"Sneak"},   // TC_ENHANCE
    {69,136,25,17,"Invisible"},   // TC_ENHANCE
    {181,99,41,17,"Sandstorm"},   // TC_ENHANCE
    {183,113,42,17,"Rainstorm"},   // TC_ENHANCE
    {180,114,43,17,"Windstorm"},   // TC_ENHANCE
    {178,115,44,17,"Firestorm"},   // TC_ENHANCE
    {179,116,45,17,"Hailstorm"},   // TC_ENHANCE
    {182,117,46,17,"Thunderstorm"},   // TC_ENHANCE
    {185,118,47,17,"Voidstorm"},   // TC_ENHANCE
    {184,119,48,17,"Aurorastorm"},   // TC_ENHANCE
    {289,308,85,17,"Animus Augeo"},   // TC_ENHANCE
    {171,309,85,17,"Animus Minuo"},   // TC_ENHANCE
    {170,495,88,17,"Adloquium"},   // TC_ENHANCE
    {0,143,39,17,"Erase"},   // TC_ENHANCE
    {113,135,35,18,"Reraise"},   // TC_HEAL
    {0,1,5,18,"Cure"},   // TC_HEAL
    {0,14,10,18,"Poisona"},   // TC_HEAL
    {0,15,12,18,"Paralyna"},   // TC_HEAL
    {0,16,17,18,"Blindna"},   // TC_HEAL
    {0,2,17,18,"Cure II"},   // TC_HEAL
    {0,17,22,18,"Silena"},   // TC_HEAL
    {0,3,30,18,"Cure III"},   // TC_HEAL
    {0,20,32,18,"Cursna"},   // TC_HEAL
    {0,12,35,18,"Raise"},   // TC_HEAL
    {0,19,46,18,"Viruna"},   // TC_HEAL
    {0,18,50,18,"Stona"},   // TC_HEAL
    {0,4,55,18,"Cure IV"},   // TC_HEAL
    {0,13,70,18,"Raise II"},   // TC_HEAL
    {0,140,91,18,"Raise III"},   // TC_HEAL
    {377,0,1,32,"Tabula Rasa"},   // TC_JA
    {359,232,10,32,"Dark Arts"},   // TC_JA
    {358,228,10,32,"Light Arts"},   // TC_JA
    {187,234,35,32,"Sublimation"},   // TC_JA
    {416,235,75,32,"Enlightenment"},   // TC_JA
    {0,230,65,32,"Modus Veritas"},   // TC_JA
    {0,237,76,32,"Libra"},   // TC_JA
    {0,254,96,32,"Caper Emissarius"},   // TC_JA
    {0,159,4,19,"Stone"},   // TC_NUKE
    {0,169,8,19,"Water"},   // TC_NUKE
    {0,154,12,19,"Aero"},   // TC_NUKE
    {0,144,16,19,"Fire"},   // TC_NUKE
    {0,278,18,19,"Geohelix"},   // TC_NUKE
    {0,149,20,19,"Blizzard"},   // TC_NUKE
    {0,279,20,19,"Hydrohelix"},   // TC_NUKE
    {0,280,22,19,"Anemohelix"},   // TC_NUKE
    {0,281,24,19,"Pyrohelix"},   // TC_NUKE
    {0,164,24,19,"Thunder"},   // TC_NUKE
    {0,282,26,19,"Cryohelix"},   // TC_NUKE
    {0,283,28,19,"Ionohelix"},   // TC_NUKE
    {0,284,30,19,"Noctohelix"},   // TC_NUKE
    {0,160,30,19,"Stone II"},   // TC_NUKE
    {0,285,32,19,"Luminohelix"},   // TC_NUKE
    {0,170,34,19,"Water II"},   // TC_NUKE
    {0,155,38,19,"Aero II"},   // TC_NUKE
    {0,145,42,19,"Fire II"},   // TC_NUKE
    {0,150,46,19,"Blizzard II"},   // TC_NUKE
    {0,165,51,19,"Thunder II"},   // TC_NUKE
    {0,161,54,19,"Stone III"},   // TC_NUKE
    {0,171,57,19,"Water III"},   // TC_NUKE
    {0,156,60,19,"Aero III"},   // TC_NUKE
    {0,146,63,19,"Fire III"},   // TC_NUKE
    {0,151,66,19,"Blizzard III"},   // TC_NUKE
    {0,166,69,19,"Thunder III"},   // TC_NUKE
    {0,162,70,19,"Stone IV"},   // TC_NUKE
    {0,172,71,19,"Water IV"},   // TC_NUKE
    {0,157,72,19,"Aero IV"},   // TC_NUKE
    {0,147,73,19,"Fire IV"},   // TC_NUKE
    {0,152,74,19,"Blizzard IV"},   // TC_NUKE
    {0,167,75,19,"Thunder IV"},   // TC_NUKE
    {0,163,79,19,"Stone V"},   // TC_NUKE
    {0,173,83,19,"Water V"},   // TC_NUKE
    {0,158,87,19,"Aero V"},   // TC_NUKE
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,148,91,19,"Fire V"},   // TC_NUKE
    {0,153,95,19,"Blizzard V"},   // TC_NUKE
    {0,168,99,19,"Thunder V"},   // TC_NUKE
    {0,887,1200,19,"Anemohelix II"},   // TC_NUKE
    {0,889,1200,19,"Cryohelix II"},   // TC_NUKE
    {0,885,1200,19,"Geohelix II"},   // TC_NUKE
    {0,886,1200,19,"Hydrohelix II"},   // TC_NUKE
    {0,890,1200,19,"Ionohelix II"},   // TC_NUKE
    {0,892,1200,19,"Luminohelix II"},   // TC_NUKE
    {0,891,1200,19,"Noctohelix II"},   // TC_NUKE
    {0,888,1200,19,"Pyrohelix II"},   // TC_NUKE
    {40,43,10,2,"Protect"},   // TC_PROTECT
    {41,48,20,2,"Shell"},   // TC_PROTECT
    {42,108,18,3,"Regen"},   // TC_REGEN
    {34,249,30,7,"Blaze Spikes"},   // TC_SPIKES
    {35,250,50,7,"Ice Spikes"},   // TC_SPIKES
    {38,251,70,7,"Shock Spikes"},   // TC_SPIKES
    {401,231,10,30,"Addendum: White"},   // TC_STRAT
    {402,231,30,30,"Addendum: Black"},   // TC_STRAT
    {0,231,10,30,"Parsimony"},   // TC_STRAT
    {0,231,10,30,"Penury"},   // TC_STRAT
    {0,231,25,30,"Alacrity"},   // TC_STRAT
    {0,231,25,30,"Celerity"},   // TC_STRAT
    {0,231,40,30,"Accession"},   // TC_STRAT
    {0,231,40,30,"Manifestation"},   // TC_STRAT
    {0,231,55,30,"Ebullience"},   // TC_STRAT
    {0,231,55,30,"Rapture"},   // TC_STRAT
    {0,231,75,30,"Altruism"},   // TC_STRAT
    {0,231,75,30,"Equanimity"},   // TC_STRAT
    {0,231,75,30,"Focalization"},   // TC_STRAT
    {0,231,75,30,"Tranquility"},   // TC_STRAT
    {0,231,87,30,"Immanence"},   // TC_STRAT
    {0,231,87,30,"Perpetuance"},   // TC_STRAT
};
static const JobBuff JT_GEO[] = {
    {0,245,15,21,"Drain"},   // TC_DARK
    {0,247,30,21,"Aspir"},   // TC_DARK
    {0,248,90,21,"Aspir II"},   // TC_DARK
    {0,881,550,21,"Aspir III"},   // TC_DARK
    {0,253,35,20,"Sleep"},   // TC_ENFEEBLE
    {0,259,70,20,"Sleep II"},   // TC_ENFEEBLE
    {540,769,1,10,"Indi-Poison"},   // TC_GEO
    {554,784,4,10,"Indi-Voidance"},   // TC_GEO
    {553,783,10,10,"Indi-Precision"},   // TC_GEO
    {539,768,15,10,"Indi-Regen"},   // TC_GEO
    {556,786,16,10,"Indi-Attunement"},   // TC_GEO
    {539,798,19,10,"Geo-Regen"},   // TC_GEO
    {555,785,22,10,"Indi-Focus"},   // TC_GEO
    {550,780,28,10,"Indi-Barrier"},   // TC_GEO
    {548,778,30,10,"Indi-CHR"},   // TC_GEO
    {541,770,30,10,"Indi-Refresh"},   // TC_GEO
    {547,777,33,10,"Indi-MND"},   // TC_GEO
    {549,779,34,10,"Indi-Fury"},   // TC_GEO
    {546,776,36,10,"Indi-INT"},   // TC_GEO
    {545,775,39,10,"Indi-AGI"},   // TC_GEO
    {552,782,40,10,"Indi-Fend"},   // TC_GEO
    {544,774,42,10,"Indi-VIT"},   // TC_GEO
    {543,773,45,10,"Indi-DEX"},   // TC_GEO
    {551,781,46,10,"Indi-Acumen"},   // TC_GEO
    {542,772,48,10,"Indi-STR"},   // TC_GEO
    {565,795,48,10,"Indi-Slow"},   // TC_GEO
    {562,792,52,10,"Indi-Torpor"},   // TC_GEO
    {561,791,58,10,"Indi-Slip"},   // TC_GEO
    {564,794,64,10,"Indi-Languor"},   // TC_GEO
    {566,796,68,10,"Indi-Paralysis"},   // TC_GEO
    {563,793,70,10,"Indi-Vex"},   // TC_GEO
    {558,788,76,10,"Indi-Frailty"},   // TC_GEO
    {557,787,82,10,"Indi-Wilt"},   // TC_GEO
    {567,797,88,10,"Indi-Gravity"},   // TC_GEO
    {560,790,88,10,"Indi-Malaise"},   // TC_GEO
    {580,771,93,10,"Indi-Haste"},   // TC_GEO
    {559,789,94,10,"Indi-Fade"},   // TC_GEO
    {0,799,5,10,"Geo-Poison"},   // TC_GEO
    {0,814,8,10,"Geo-Voidance"},   // TC_GEO
    {0,813,14,10,"Geo-Precision"},   // TC_GEO
    {0,816,20,10,"Geo-Attunement"},   // TC_GEO
    {0,815,26,10,"Geo-Focus"},   // TC_GEO
    {0,810,32,10,"Geo-Barrier"},   // TC_GEO
    {0,808,34,10,"Geo-CHR"},   // TC_GEO
    {0,800,34,10,"Geo-Refresh"},   // TC_GEO
    {0,807,37,10,"Geo-MND"},   // TC_GEO
    {0,809,38,10,"Geo-Fury"},   // TC_GEO
    {0,806,40,10,"Geo-INT"},   // TC_GEO
    {0,805,43,10,"Geo-AGI"},   // TC_GEO
    {0,812,44,10,"Geo-Fend"},   // TC_GEO
    {0,804,46,10,"Geo-VIT"},   // TC_GEO
    {0,803,49,10,"Geo-DEX"},   // TC_GEO
    {0,811,50,10,"Geo-Acumen"},   // TC_GEO
    {0,802,52,10,"Geo-STR"},   // TC_GEO
    {0,825,52,10,"Geo-Slow"},   // TC_GEO
    {0,822,56,10,"Geo-Torpor"},   // TC_GEO
    {0,821,62,10,"Geo-Slip"},   // TC_GEO
    {0,824,68,10,"Geo-Languor"},   // TC_GEO
    {0,826,72,10,"Geo-Paralysis"},   // TC_GEO
    {0,823,74,10,"Geo-Vex"},   // TC_GEO
    {0,818,80,10,"Geo-Frailty"},   // TC_GEO
    {0,817,86,10,"Geo-Wilt"},   // TC_GEO
    {0,827,92,10,"Geo-Gravity"},   // TC_GEO
    {0,820,92,10,"Geo-Malaise"},   // TC_GEO
    {0,801,97,10,"Geo-Haste"},   // TC_GEO
    {0,819,98,10,"Geo-Fade"},   // TC_GEO
    {513,0,1,32,"Bolster"},   // TC_JA
    {517,245,40,32,"Collimated Fervor"},   // TC_JA
    {569,247,60,32,"Blaze of Glory"},   // TC_JA
    {518,248,70,32,"Dematerialize"},   // TC_JA
    {584,93,75,32,"Entrust"},   // TC_JA
    {59,249,80,32,"Theurgic Focus"},   // TC_JA
    {508,130,96,32,"Widened Compass"},   // TC_JA
    {0,243,5,32,"Full Circle"},   // TC_JA
    {0,244,25,32,"Ecliptic Attrition"},   // TC_JA
    {0,244,25,32,"Lasting Emanation"},   // TC_JA
    {0,246,50,32,"Life Cycle"},   // TC_JA
    {0,251,75,32,"Mending Halation"},   // TC_JA
    {0,252,75,32,"Radial Arcana"},   // TC_JA
    {0,250,90,32,"Concentric Pulse"},   // TC_JA
    {0,159,4,19,"Stone"},   // TC_NUKE
    {0,169,9,19,"Water"},   // TC_NUKE
    {0,154,14,19,"Aero"},   // TC_NUKE
    {0,144,19,19,"Fire"},   // TC_NUKE
    {0,149,24,19,"Blizzard"},   // TC_NUKE
    {0,834,25,19,"Stonera"},   // TC_NUKE
    {0,164,29,19,"Thunder"},   // TC_NUKE
    {0,838,30,19,"Watera"},   // TC_NUKE
    {0,160,34,19,"Stone II"},   // TC_NUKE
    {0,832,35,19,"Aera"},   // TC_NUKE
    {0,170,38,19,"Water II"},   // TC_NUKE
    {0,828,40,19,"Fira"},   // TC_NUKE
    {0,155,42,19,"Aero II"},   // TC_NUKE
    {0,830,45,19,"Blizzara"},   // TC_NUKE
    {0,145,46,19,"Fire II"},   // TC_NUKE
    {0,150,50,19,"Blizzard II"},   // TC_NUKE
    {0,836,50,19,"Thundara"},   // TC_NUKE
    {0,165,54,19,"Thunder II"},   // TC_NUKE
    {0,161,58,19,"Stone III"},   // TC_NUKE
    {0,171,61,19,"Water III"},   // TC_NUKE
    {0,156,64,19,"Aero III"},   // TC_NUKE
    {0,146,67,19,"Fire III"},   // TC_NUKE
    {0,151,70,19,"Blizzard III"},   // TC_NUKE
    {0,835,70,19,"Stonera II"},   // TC_NUKE
    {0,166,73,19,"Thunder III"},   // TC_NUKE
    {0,839,75,19,"Watera II"},   // TC_NUKE
    {0,162,76,19,"Stone IV"},   // TC_NUKE
    {0,172,79,19,"Water IV"},   // TC_NUKE
    {0,833,80,19,"Aera II"},   // TC_NUKE
    {0,157,82,19,"Aero IV"},   // TC_NUKE
    {0,829,85,19,"Fira II"},   // TC_NUKE
    {0,147,85,19,"Fire IV"},   // TC_NUKE
    {0,152,88,19,"Blizzard IV"},   // TC_NUKE
    {0,831,90,19,"Blizzara II"},   // TC_NUKE
    {0,503,90,19,"Impact"},   // TC_NUKE
    {0,167,91,19,"Thunder IV"},   // TC_NUKE
    {0,837,95,19,"Thundara II"},   // TC_NUKE
    {0,158,100,19,"Aero V"},   // TC_NUKE
    {0,153,100,19,"Blizzard V"},   // TC_NUKE
    {0,148,100,19,"Fire V"},   // TC_NUKE
    {0,163,100,19,"Stone V"},   // TC_NUKE
    {0,168,100,19,"Thunder V"},   // TC_NUKE
    {0,173,100,19,"Water V"},   // TC_NUKE
    {0,867,1200,19,"Aera III"},   // TC_NUKE
    {0,866,1200,19,"Blizzara III"},   // TC_NUKE
    {0,865,1200,19,"Fira III"},   // TC_NUKE
    {0,868,1200,19,"Stonera III"},   // TC_NUKE
    {0,869,1200,19,"Thundara III"},   // TC_NUKE
    {0,870,1200,19,"Watera III"},   // TC_NUKE
};
static const JobBuff JT_RUN[] = {
    {103,63,4,5,"Barstone"},   // TC_BARSPELL
    {106,72,6,5,"Barsleep"},   // TC_BARSPELL
    {105,65,8,5,"Barwater"},   // TC_BARSPELL
    {107,73,9,5,"Barpoison"},   // TC_BARSPELL
    {108,74,11,5,"Barparalyze"},   // TC_BARSPELL
    {102,62,12,5,"Baraero"},   // TC_BARSPELL
    {100,60,16,5,"Barfire"},   // TC_BARSPELL
    {109,75,17,5,"Barblind"},   // TC_BARSPELL
    {101,61,20,5,"Barblizzard"},   // TC_BARSPELL
    {110,76,22,5,"Barsilence"},   // TC_BARSPELL
    {104,64,24,5,"Barthunder"},   // TC_BARSPELL
    {112,78,38,5,"Barvirus"},   // TC_BARSPELL
    {111,77,42,5,"Barpetrify"},   // TC_BARSPELL
    {286,84,76,5,"Baramnesia"},   // TC_BARSPELL
    {39,55,15,8,"Aquaveil"},   // TC_DEFENSE
    {36,53,35,8,"Blink"},   // TC_DEFENSE
    {37,54,55,8,"Stoneskin"},   // TC_DEFENSE
    {116,106,68,8,"Phalanx"},   // TC_DEFENSE
    {0,112,45,22,"Flash"},   // TC_DIVINE
    {568,840,58,17,"Foil"},   // TC_ENHANCE
    {289,476,88,17,"Crusade"},   // TC_ENHANCE
    {432,493,550,17,"Temper"},   // TC_ENHANCE
    {522,0,1,32,"Elemental Sforzo"},   // TC_JA
    {532,24,20,32,"Swordplay"},   // TC_JA
    {534,72,60,32,"Embolden"},   // TC_JA
    {152,118,95,32,"One for All"},   // TC_JA
    {0,242,65,32,"Vivacious Pulse"},   // TC_JA
    {0,131,96,32,"Odyllic Subterfuge"},   // TC_JA
    {41,48,10,2,"Shell"},   // TC_PROTECT
    {40,43,20,2,"Protect"},   // TC_PROTECT
    {43,109,62,0,"Refresh"},   // TC_REFRESH
    {42,108,23,3,"Regen"},   // TC_REGEN
    {525,10,5,28,"Flabra"},   // TC_RUNE
    {524,10,5,28,"Gelus"},   // TC_RUNE
    {523,10,5,28,"Ignis"},   // TC_RUNE
    {529,10,5,28,"Lux"},   // TC_RUNE
    {527,10,5,28,"Sulpor"},   // TC_RUNE
    {526,10,5,28,"Tellus"},   // TC_RUNE
    {530,10,5,28,"Tenebrae"},   // TC_RUNE
    {528,10,5,28,"Unda"},   // TC_RUNE
    {34,249,45,7,"Blaze Spikes"},   // TC_SPIKES
    {35,250,65,7,"Ice Spikes"},   // TC_SPIKES
    {38,251,85,7,"Shock Spikes"},   // TC_SPIKES
    {531,23,10,29,"Vallation"},   // TC_WARD
    {533,59,40,29,"Pflug"},   // TC_WARD
    {535,113,50,29,"Valiance"},   // TC_WARD
    {570,120,75,29,"Battuta"},   // TC_WARD
    {537,117,85,29,"Liement"},   // TC_WARD
    {0,25,25,29,"Lunge"},   // TC_WARD
    {0,241,25,29,"Swipe"},   // TC_WARD
    {0,116,70,29,"Gambit"},   // TC_WARD
    {0,119,75,29,"Rayke"},   // TC_WARD
};
// GLOBAL buff families (job-agnostic) : one row per distinct buff STATUS, for the family-organised filter.
struct BuffFam { unsigned short status; unsigned char cat; const char* name; };
static const BuffFam BUFF_FAM[] = {
    {43,0,"Refresh"},   // TC_REFRESH
    {581,1,"Flurry"},   // TC_HASTE
    {33,1,"Haste"},   // TC_HASTE
    {40,2,"Protect"},   // TC_PROTECT
    {41,2,"Shell"},   // TC_PROTECT
    {42,3,"Regen"},   // TC_REGEN
    {96,4,"Enaero"},   // TC_ENSPELL
    {95,4,"Enblizzard"},   // TC_ENSPELL
    {94,4,"Enfire"},   // TC_ENSPELL
    {97,4,"Enstone"},   // TC_ENSPELL
    {98,4,"Enthunder"},   // TC_ENSPELL
    {99,4,"Enwater"},   // TC_ENSPELL
    {102,5,"Baraera"},   // TC_BARSPELL
    {286,5,"Baramnesra"},   // TC_BARSPELL
    {109,5,"Barblind"},   // TC_BARSPELL
    {101,5,"Barblizzara"},   // TC_BARSPELL
    {100,5,"Barfira"},   // TC_BARSPELL
    {108,5,"Barparalyze"},   // TC_BARSPELL
    {111,5,"Barpetra"},   // TC_BARSPELL
    {107,5,"Barpoison"},   // TC_BARSPELL
    {110,5,"Barsilence"},   // TC_BARSPELL
    {106,5,"Barsleep"},   // TC_BARSPELL
    {103,5,"Barstone"},   // TC_BARSPELL
    {104,5,"Barthundra"},   // TC_BARSPELL
    {112,5,"Barvira"},   // TC_BARSPELL
    {105,5,"Barwater"},   // TC_BARSPELL
    {86,6,"Boost-CHR"},   // TC_GAIN
    {122,6,"Gain-AGI"},   // TC_GAIN
    {125,6,"Gain-CHR"},   // TC_GAIN
    {120,6,"Gain-DEX"},   // TC_GAIN
    {123,6,"Gain-INT"},   // TC_GAIN
    {124,6,"Gain-MND"},   // TC_GAIN
    {119,6,"Gain-STR"},   // TC_GAIN
    {121,6,"Gain-VIT"},   // TC_GAIN
    {34,7,"Blaze Spikes"},   // TC_SPIKES
    {35,7,"Ice Spikes"},   // TC_SPIKES
    {38,7,"Shock Spikes"},   // TC_SPIKES
    {39,8,"Aquaveil"},   // TC_DEFENSE
    {36,8,"Blink"},   // TC_DEFENSE
    {116,8,"Phalanx"},   // TC_DEFENSE
    {37,8,"Stoneskin"},   // TC_DEFENSE
    {221,9,"Adventurer's Dirge"},   // TC_SONG
    {213,9,"Aria of Passion"},   // TC_SONG
    {195,9,"Army's Paeon"},   // TC_SONG
    {220,9,"Foe Sirvente"},   // TC_SONG
    {202,9,"Fowl Aubade"},   // TC_SONG
    {210,9,"Goblin Gavotte"},   // TC_SONG
    {218,9,"Goddess's Hymnus"},   // TC_SONG
    {207,9,"Gold Capriccio"},   // TC_SONG
    {203,9,"Herb Pastoral"},   // TC_SONG
    {214,9,"Honor March"},   // TC_SONG
    {200,9,"Hunter's Prelude"},   // TC_SONG
    {216,9,"Ice Carol"},   // TC_SONG
    {197,9,"Knight's Minne"},   // TC_SONG
    {196,9,"Mage's Ballad"},   // TC_SONG
    {219,9,"Raptor Mazurka"},   // TC_SONG
    {215,9,"Sage Etude"},   // TC_SONG
    {206,9,"Scop's Operetta"},   // TC_SONG
    {222,9,"Sentinel's Scherzo"},   // TC_SONG
    {201,9,"Sheepfoe Mambo"},   // TC_SONG
    {205,9,"Shining Fantasia"},   // TC_SONG
    {199,9,"Sword Madrigal"},   // TC_SONG
    {198,9,"Valor Minuet"},   // TC_SONG
    {209,9,"Warding Round"},   // TC_SONG
    {539,10,"Geo-Regen"},   // TC_GEO
    {551,10,"Indi-Acumen"},   // TC_GEO
    {545,10,"Indi-AGI"},   // TC_GEO
    {556,10,"Indi-Attunement"},   // TC_GEO
    {550,10,"Indi-Barrier"},   // TC_GEO
    {548,10,"Indi-CHR"},   // TC_GEO
    {543,10,"Indi-DEX"},   // TC_GEO
    {559,10,"Indi-Fade"},   // TC_GEO
    {552,10,"Indi-Fend"},   // TC_GEO
    {555,10,"Indi-Focus"},   // TC_GEO
    {558,10,"Indi-Frailty"},   // TC_GEO
    {549,10,"Indi-Fury"},   // TC_GEO
    {567,10,"Indi-Gravity"},   // TC_GEO
    {580,10,"Indi-Haste"},   // TC_GEO
    {546,10,"Indi-INT"},   // TC_GEO
    {564,10,"Indi-Languor"},   // TC_GEO
    {560,10,"Indi-Malaise"},   // TC_GEO
    {547,10,"Indi-MND"},   // TC_GEO
    {566,10,"Indi-Paralysis"},   // TC_GEO
    {540,10,"Indi-Poison"},   // TC_GEO
    {553,10,"Indi-Precision"},   // TC_GEO
    {541,10,"Indi-Refresh"},   // TC_GEO
    {561,10,"Indi-Slip"},   // TC_GEO
    {565,10,"Indi-Slow"},   // TC_GEO
    {542,10,"Indi-STR"},   // TC_GEO
    {562,10,"Indi-Torpor"},   // TC_GEO
    {563,10,"Indi-Vex"},   // TC_GEO
    {544,10,"Indi-VIT"},   // TC_GEO
    {554,10,"Indi-Voidance"},   // TC_GEO
    {557,10,"Indi-Wilt"},   // TC_GEO
    {289,11,"Gekka: Ichi"},   // TC_NINJUTSU
    {227,11,"Kakka: Ichi"},   // TC_NINJUTSU
    {471,11,"Migawari: Ichi"},   // TC_NINJUTSU
    {71,11,"Monomi: Ichi"},   // TC_NINJUTSU
    {290,11,"Myoshu: Ichi"},   // TC_NINJUTSU
    {69,11,"Tonko: Ni"},   // TC_NINJUTSU
    {171,11,"Yain: Ichi"},   // TC_NINJUTSU
    {116,13,"Barrier Tusk"},   // TC_BLU_BUFF
    {43,13,"Battery Charge"},   // TC_BLU_BUFF
    {93,13,"Cocoon"},   // TC_BLU_BUFF
    {37,13,"Diamondhide"},   // TC_BLU_BUFF
    {45,13,"Fantod"},   // TC_BLU_BUFF
    {92,13,"Feather Barrier"},   // TC_BLU_BUFF
    {152,13,"Magic Barrier"},   // TC_BLU_BUFF
    {190,13,"Memento Mori"},   // TC_BLU_BUFF
    {604,13,"Mighty Guard"},   // TC_BLU_BUFF
    {486,13,"O. Counterstance"},   // TC_BLU_BUFF
    {36,13,"Occultation"},   // TC_BLU_BUFF
    {38,13,"Plasma Charge"},   // TC_BLU_BUFF
    {150,13,"Pyric Bulwark"},   // TC_BLU_BUFF
    {33,13,"Refueling"},   // TC_BLU_BUFF
    {42,13,"Regeneration"},   // TC_BLU_BUFF
    {191,13,"Saline Coat"},   // TC_BLU_BUFF
    {91,13,"Triumphant Roar"},   // TC_BLU_BUFF
    {170,17,"Adloquium"},   // TC_ENHANCE
    {171,17,"Animus Minuo"},   // TC_ENHANCE
    {184,17,"Aurorastorm"},   // TC_ENHANCE
    {275,17,"Auspice"},   // TC_ENHANCE
    {289,17,"Crusade"},   // TC_ENHANCE
    {70,17,"Deodorize"},   // TC_ENHANCE
    {228,17,"Embrava"},   // TC_ENHANCE
    {178,17,"Firestorm"},   // TC_ENHANCE
    {568,17,"Foil"},   // TC_ENHANCE
    {179,17,"Hailstorm"},   // TC_ENHANCE
    {69,17,"Invisible"},   // TC_ENHANCE
    {183,17,"Rainstorm"},   // TC_ENHANCE
    {403,17,"Reprisal"},   // TC_ENHANCE
    {181,17,"Sandstorm"},   // TC_ENHANCE
    {71,17,"Sneak"},   // TC_ENHANCE
    {432,17,"Temper"},   // TC_ENHANCE
    {182,17,"Thunderstorm"},   // TC_ENHANCE
    {185,17,"Voidstorm"},   // TC_ENHANCE
    {180,17,"Windstorm"},   // TC_ENHANCE
    {113,18,"Reraise"},   // TC_HEAL
    {173,21,"Dread Spikes"},   // TC_DARK
    {288,21,"Endark"},   // TC_DARK
    {407,21,"Klimaform"},   // TC_DARK
    {274,22,"Enlight"},   // TC_DIVINE
    {335,25,"Allies' Roll"},   // TC_ROLL
    {338,25,"Avenger's Roll"},   // TC_ROLL
    {318,25,"Beast Roll"},   // TC_ROLL
    {333,25,"Blitzer's Roll"},   // TC_ROLL
    {330,25,"Bolter's Roll"},   // TC_ROLL
    {331,25,"Caster's Roll"},   // TC_ROLL
    {317,25,"Chaos Roll"},   // TC_ROLL
    {319,25,"Choral Roll"},   // TC_ROLL
    {337,25,"Companion's Roll"},   // TC_ROLL
    {326,25,"Corsair's Roll"},   // TC_ROLL
    {332,25,"Courser's Roll"},   // TC_ROLL
    {328,25,"Dancer's Roll"},   // TC_ROLL
    {323,25,"Drachen Roll"},   // TC_ROLL
    {324,25,"Evoker's Roll"},   // TC_ROLL
    {310,25,"Fighter's Roll"},   // TC_ROLL
    {316,25,"Gallant's Roll"},   // TC_ROLL
    {312,25,"Healer's Roll"},   // TC_ROLL
    {320,25,"Hunter's Roll"},   // TC_ROLL
    {325,25,"Magus's Roll"},   // TC_ROLL
    {336,25,"Miser's Roll"},   // TC_ROLL
    {311,25,"Monk's Roll"},   // TC_ROLL
    {339,25,"Naturalist's Roll"},   // TC_ROLL
    {322,25,"Ninja Roll"},   // TC_ROLL
    {327,25,"Puppet Roll"},   // TC_ROLL
    {315,25,"Rogue's Roll"},   // TC_ROLL
    {600,25,"Runeist's Roll"},   // TC_ROLL
    {321,25,"Samurai Roll"},   // TC_ROLL
    {329,25,"Scholar's Roll"},   // TC_ROLL
    {334,25,"Tactician's Roll"},   // TC_ROLL
    {314,25,"Warlock's Roll"},   // TC_ROLL
    {313,25,"Wizard's Roll"},   // TC_ROLL
    {369,26,"Aspir Samba"},   // TC_SAMBA
    {368,26,"Drain Samba"},   // TC_SAMBA
    {370,26,"Haste Samba"},   // TC_SAMBA
    {375,27,"Building Flourish"},   // TC_DANCE
    {176,27,"Chocobo Jig"},   // TC_DANCE
    {443,27,"Climactic Flourish"},   // TC_DANCE
    {468,27,"Striking Flourish"},   // TC_DANCE
    {472,27,"Ternary Flourish"},   // TC_DANCE
    {525,28,"Flabra"},   // TC_RUNE
    {524,28,"Gelus"},   // TC_RUNE
    {523,28,"Ignis"},   // TC_RUNE
    {529,28,"Lux"},   // TC_RUNE
    {527,28,"Sulpor"},   // TC_RUNE
    {526,28,"Tellus"},   // TC_RUNE
    {530,28,"Tenebrae"},   // TC_RUNE
    {528,28,"Unda"},   // TC_RUNE
    {570,29,"Battuta"},   // TC_WARD
    {537,29,"Liement"},   // TC_WARD
    {533,29,"Pflug"},   // TC_WARD
    {535,29,"Valiance"},   // TC_WARD
    {531,29,"Vallation"},   // TC_WARD
    {402,30,"Addendum: Black"},   // TC_STRAT
    {401,30,"Addendum: White"},   // TC_STRAT
    {36,31,"Aerial Armor"},   // TC_BPACT
    {39,31,"Chinook"},   // TC_BPACT
    {68,31,"Crimson Howl"},   // TC_BPACT
    {587,31,"Crystal Blessing"},   // TC_BPACT
    {190,31,"Dream Shroud"},   // TC_BPACT
    {458,31,"Earthen Armor"},   // TC_BPACT
    {37,31,"Earthen Ward"},   // TC_BPACT
    {176,31,"Fleet Wind"},   // TC_BPACT
    {35,31,"Frost Armor"},   // TC_BPACT
    {33,31,"Hastega"},   // TC_BPACT
    {94,31,"Inferno Howl"},   // TC_BPACT
    {96,31,"Katabatic Blades"},   // TC_BPACT
    {38,31,"Lightning Armor"},   // TC_BPACT
    {116,31,"Noctoshield"},   // TC_BPACT
    {113,31,"Reraise II"},   // TC_BPACT
    {98,31,"Rolling Thunder"},   // TC_BPACT
    {154,31,"Shining Ruby"},   // TC_BPACT
    {586,31,"Soothing Current"},   // TC_BPACT
    {152,31,"Wind's Blessing"},   // TC_BPACT
    {418,32,"Afflatus Misery"},   // TC_JA
    {417,32,"Afflatus Solace"},   // TC_JA
    {58,32,"Aggressor"},   // TC_JA
    {118,32,"Ancient Circle"},   // TC_JA
    {583,32,"Apogee"},   // TC_JA
    {75,32,"Arcane Circle"},   // TC_JA
    {342,32,"Assassin's Charge"},   // TC_JA
    {504,32,"Astral Conduit"},   // TC_JA
    {55,32,"Astral Flow"},   // TC_JA
    {492,32,"Asylum"},   // TC_JA
    {163,32,"Azure Lore"},   // TC_JA
    {73,32,"Barrage"},   // TC_JA
    {56,32,"Berserk"},   // TC_JA
    {569,32,"Blaze of Glory"},   // TC_JA
    {460,32,"Blood Rage"},   // TC_JA
    {51,32,"Blood Weapon"},   // TC_JA
    {513,32,"Bolster"},   // TC_JA
    {490,32,"Brazen Rush"},   // TC_JA
    {165,32,"Burst Affinity"},   // TC_JA
    {598,32,"Cascade"},   // TC_JA
    {164,32,"Chain Affinity"},   // TC_JA
    {48,32,"Chainspell"},   // TC_JA
    {499,32,"Clarion Call"},   // TC_JA
    {517,32,"Collimated Fervor"},   // TC_JA
    {419,32,"Composure"},   // TC_JA
    {462,32,"Conspirator"},   // TC_JA
    {599,32,"Consume Mana"},   // TC_JA
    {582,32,"Contradance"},   // TC_JA
    {355,32,"Convergence"},   // TC_JA
    {61,32,"Counterstance"},   // TC_JA
    {114,32,"Cover"},   // TC_JA
    {601,32,"Crooked Cards"},   // TC_JA
    {359,32,"Dark Arts"},   // TC_JA
    {345,32,"Dark Seal"},   // TC_JA
    {482,32,"Decoy Shot"},   // TC_JA
    {57,32,"Defender"},   // TC_JA
    {518,32,"Dematerialize"},   // TC_JA
    {346,32,"Diabolic Eye"},   // TC_JA
    {356,32,"Diffusion"},   // TC_JA
    {453,32,"Divine Caress"},   // TC_JA
    {438,32,"Divine Emblem"},   // TC_JA
    {78,32,"Divine Seal"},   // TC_JA
    {60,32,"Dodge"},   // TC_JA
    {433,32,"Double Shot"},   // TC_JA
    {457,32,"Efflux"},   // TC_JA
    {79,32,"Elemental Seal"},   // TC_JA
    {522,32,"Elemental Sforzo"},   // TC_JA
    {534,32,"Embolden"},   // TC_JA
    {416,32,"Enlightenment"},   // TC_JA
    {584,32,"Entrust"},   // TC_JA
    {411,32,"Fan Dance"},   // TC_JA
    {344,32,"Fealty"},   // TC_JA
    {343,32,"Feint"},   // TC_JA
    {351,32,"Flashy Shot"},   // TC_JA
    {32,32,"Flee"},   // TC_JA
    {503,32,"Fly High"},   // TC_JA
    {59,32,"Focus"},   // TC_JA
    {406,32,"Footwork"},   // TC_JA
    {341,32,"Formless Strikes"},   // TC_JA
    {441,32,"Futae"},   // TC_JA
    {507,32,"Grand Pas"},   // TC_JA
    {483,32,"Hagakure"},   // TC_JA
    {353,32,"Hasso"},   // TC_JA
    {74,32,"Holy Circle"},   // TC_JA
    {46,32,"Hundred Fists"},   // TC_JA
    {461,32,"Impetus"},   // TC_JA
    {491,32,"Inner Strength"},   // TC_JA
    {421,32,"Innin"},   // TC_JA
    {50,32,"Invincible"},   // TC_JA
    {484,32,"Issekigan"},   // TC_JA
    {349,32,"Killer Instinct"},   // TC_JA
    {64,32,"Last Resort"},   // TC_JA
    {358,32,"Light Arts"},   // TC_JA
    {621,32,"Majesty"},   // TC_JA
    {437,32,"Mana Wall"},   // TC_JA
    {47,32,"Manafont"},   // TC_JA
    {229,32,"Manawell"},   // TC_JA
    {88,32,"Mantra"},   // TC_JA
    {231,32,"Marcato"},   // TC_JA
    {54,32,"Meikyo Shisui"},   // TC_JA
    {44,32,"Mighty Strikes"},   // TC_JA
    {502,32,"Mikage"},   // TC_JA
    {439,32,"Nether Void"},   // TC_JA
    {347,32,"Nightingale"},   // TC_JA
    {152,32,"One for All"},   // TC_JA
    {166,32,"Overdrive"},   // TC_JA
    {500,32,"Overkill"},   // TC_JA
    {478,32,"Palisade"},   // TC_JA
    {436,32,"Perfect Counter"},   // TC_JA
    {49,32,"Perfect Dodge"},   // TC_JA
    {409,32,"Pianissimo"},   // TC_JA
    {442,32,"Presto"},   // TC_JA
    {93,32,"Rampart"},   // TC_JA
    {435,32,"Restraint"},   // TC_JA
    {405,32,"Retaliation"},   // TC_JA
    {410,32,"Saber Dance"},   // TC_JA
    {454,32,"Saboteur"},   // TC_JA
    {477,32,"Sacrosanctity"},   // TC_JA
    {352,32,"Sange"},   // TC_JA
    {479,32,"Scarlet Delirium"},   // TC_JA
    {354,32,"Seigan"},   // TC_JA
    {440,32,"Sengikori"},   // TC_JA
    {62,32,"Sentinel"},   // TC_JA
    {72,32,"Sharpshot"},   // TC_JA
    {357,32,"Snake Eye"},   // TC_JA
    {65,32,"Sneak Attack"},   // TC_JA
    {497,32,"Soul Enslavement"},   // TC_JA
    {52,32,"Soul Voice"},   // TC_JA
    {63,32,"Souleater"},   // TC_JA
    {126,32,"Spirit Surge"},   // TC_JA
    {230,32,"Spontaneity"},   // TC_JA
    {350,32,"Stealth Shot"},   // TC_JA
    {494,32,"Stymie"},   // TC_JA
    {187,32,"Sublimation"},   // TC_JA
    {493,32,"Subtle Sorcery"},   // TC_JA
    {532,32,"Swordplay"},   // TC_JA
    {377,32,"Tabula Rasa"},   // TC_JA
    {455,32,"Tenuto"},   // TC_JA
    {67,32,"Third Eye"},   // TC_JA
    {376,32,"Trance"},   // TC_JA
    {87,32,"Trick Attack"},   // TC_JA
    {467,32,"Triple Shot"},   // TC_JA
    {348,32,"Troubadour"},   // TC_JA
    {485,32,"Unbridled Learning"},   // TC_JA
    {505,32,"Unbridled Wisdom"},   // TC_JA
    {498,32,"Unleash"},   // TC_JA
    {115,32,"Unlimited Shot"},   // TC_JA
    {371,32,"Velocity Shot"},   // TC_JA
    {68,32,"Warcry"},   // TC_JA
    {117,32,"Warding Circle"},   // TC_JA
    {340,32,"Warrior's Charge"},   // TC_JA
    {508,32,"Widened Compass"},   // TC_JA
    {501,32,"Yaegasumi"},   // TC_JA
    {420,32,"Yonin"},   // TC_JA
    {251,33,"Food"},   // TC_FOOD
    {270,34,"Aftermath: Lv.1"},   // TC_AFTERMATH
    {271,34,"Aftermath: Lv.2"},   // TC_AFTERMATH
    {272,34,"Aftermath: Lv.3"},   // TC_AFTERMATH
    {512,35,"Ionis"},   // TC_SIGNET
    {256,35,"Sanction"},   // TC_SIGNET
    {268,35,"Sigil"},   // TC_SIGNET
    {253,35,"Signet"},   // TC_SIGNET
    {242,36,"Alchemy"},   // TC_CRAFT
    {241,36,"Bonecraft"},   // TC_CRAFT
    {239,36,"Clothcraft"},   // TC_CRAFT
    {243,36,"Cooking"},   // TC_CRAFT
    {235,36,"Fishing"},   // TC_CRAFT
    {238,36,"Goldsmithing"},   // TC_CRAFT
    {240,36,"Leathercraft"},   // TC_CRAFT
    {237,36,"Smithing"},   // TC_CRAFT
    {236,36,"Woodworking"},   // TC_CRAFT
};
static const int BUFF_FAM_N = (int)(sizeof(BUFF_FAM) / sizeof(BUFF_FAM[0]));
struct JobTrack { const JobBuff* buffs; int n; };
static const JobTrack JOB_TRACK[24] = {
    {0, 0},   // -
    {JT_WAR, 12},   // WAR
    {JT_MNK, 13},   // MNK
    {JT_WHM, 99},   // WHM
    {JT_BLM, 115},   // BLM
    {JT_RDM, 119},   // RDM
    {JT_THF, 15},   // THF
    {JT_PLD, 30},   // PLD
    {JT_DRK, 59},   // DRK
    {JT_BST, 19},   // BST
    {JT_BRD, 89},   // BRD
    {JT_RNG, 15},   // RNG
    {JT_SAM, 14},   // SAM
    {JT_NIN, 44},   // NIN
    {JT_DRG, 18},   // DRG
    {JT_SMN, 74},   // SMN
    {JT_BLU, 204},   // BLU
    {JT_COR, 40},   // COR
    {JT_PUP, 21},   // PUP
    {JT_DNC, 37},   // DNC
    {JT_SCH, 120},   // SCH
    {JT_GEO, 129},   // GEO
    {JT_RUN, 52},   // RUN
    {0, 0},   // MON
};
inline const JobBuff* job_track(unsigned job, int& n) {
    if (job < 1 || job > 23) { n = 0; return 0; }
    n = JOB_TRACK[job].n; return JOB_TRACK[job].buffs; }
} // namespace aio
