// overwrites_gen.h -- GENERATED by scripts/gen_overwrites.py from res/spells.lua. Do NOT hand-edit.
// spell id -> the spell ids it OVERWRITES. FFXI refuses a weaker debuff while a stronger one is up, and
// replaces the weaker one when the stronger lands. The relation CROSSES families (Dia III overwrites Bio I/II),
// so it cannot be derived from the status id. Consumed by PartyState::record_debuff.
#pragma once
namespace aio {
// `strict` : bit i of the list is set when THAT edge is a real strength order (b cannot reach a back).
// Only a strict edge may refuse a cast ; the cyclic ones (elemental DoT ring, mutual Threnody II) still
// remove, they just never prove which of the two is stronger -- because neither is.
struct SpellOverwrite { unsigned short spell; unsigned char n; unsigned short strict; unsigned short list[15]; };
static const SpellOverwrite SPELL_OVERWRITES[] = {
    {24,2,0x0003,{23,230,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Dia II
    {25,4,0x000F,{23,24,230,231,0,0,0,0,0,0,0,0,0,0,0}},   // Dia III
    {26,6,0x003F,{23,24,25,230,231,232,0,0,0,0,0,0,0,0,0}},   // Dia IV
    {27,7,0x007F,{23,24,25,26,230,231,232,0,0,0,0,0,0,0,0}},   // Dia V
    {44,1,0x0001,{43,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protect II
    {45,2,0x0003,{43,44,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protect III
    {46,3,0x0007,{43,44,45,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protect IV
    {47,4,0x000F,{43,44,45,46,0,0,0,0,0,0,0,0,0,0,0}},   // Protect V
    {49,1,0x0001,{48,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shell II
    {50,2,0x0003,{48,49,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shell III
    {51,3,0x0007,{48,49,50,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shell IV
    {52,4,0x000F,{48,49,50,51,0,0,0,0,0,0,0,0,0,0,0}},   // Shell V
    {57,1,0x0000,{845,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Haste
    {60,5,0x0000,{61,62,63,64,65,0,0,0,0,0,0,0,0,0,0}},   // Barfire
    {61,5,0x0000,{60,62,63,64,65,0,0,0,0,0,0,0,0,0,0}},   // Barblizzard
    {62,5,0x0000,{60,61,63,64,65,0,0,0,0,0,0,0,0,0,0}},   // Baraero
    {63,5,0x0000,{60,61,62,64,65,0,0,0,0,0,0,0,0,0,0}},   // Barstone
    {64,5,0x0000,{60,61,62,63,65,0,0,0,0,0,0,0,0,0,0}},   // Barthunder
    {65,5,0x0000,{60,61,62,63,64,0,0,0,0,0,0,0,0,0,0}},   // Barwater
    {66,5,0x0000,{67,68,69,70,71,0,0,0,0,0,0,0,0,0,0}},   // Barfira
    {67,5,0x0000,{66,68,69,70,71,0,0,0,0,0,0,0,0,0,0}},   // Barblizzara
    {68,5,0x0000,{66,67,69,70,71,0,0,0,0,0,0,0,0,0,0}},   // Baraera
    {69,5,0x0000,{66,67,68,70,71,0,0,0,0,0,0,0,0,0,0}},   // Barstonra
    {70,5,0x0000,{66,67,68,69,71,0,0,0,0,0,0,0,0,0,0}},   // Barthundra
    {71,5,0x0000,{66,67,68,69,70,0,0,0,0,0,0,0,0,0,0}},   // Barwatera
    {79,4,0x000F,{56,344,345,346,0,0,0,0,0,0,0,0,0,0,0}},   // Slow II
    {80,4,0x000F,{58,341,342,343,0,0,0,0,0,0,0,0,0,0,0}},   // Paralyze II
    {98,1,0x0001,{253,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Repose
    {99,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Sandstorm
    {100,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enfire
    {101,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enblizzard
    {102,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enaero
    {103,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enstone
    {104,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enthunder
    {105,6,0x0000,{100,101,102,103,104,105,0,0,0,0,0,0,0,0,0}},   // Enwater
    {113,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Rainstorm
    {114,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Windstorm
    {115,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Firestorm
    {116,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Hailstorm
    {117,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Thunderstorm
    {118,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Voidstorm
    {119,8,0x0000,{99,113,114,115,116,117,118,119,0,0,0,0,0,0,0}},   // Aurorastorm
    {126,1,0x0001,{125,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protectra II
    {127,2,0x0003,{125,126,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protectra III
    {128,3,0x0007,{125,126,127,0,0,0,0,0,0,0,0,0,0,0,0}},   // Protectra IV
    {129,4,0x000F,{125,126,127,128,0,0,0,0,0,0,0,0,0,0,0}},   // Protectra V
    {131,1,0x0001,{130,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shellra II
    {132,2,0x0003,{130,131,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shellra III
    {133,3,0x0007,{130,131,132,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shellra IV
    {134,4,0x000F,{130,131,132,133,0,0,0,0,0,0,0,0,0,0,0}},   // Shellra V
    {217,1,0x0001,{216,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Gravity II
    {221,4,0x000F,{220,350,351,352,0,0,0,0,0,0,0,0,0,0,0}},   // Poison II
    {222,5,0x001F,{220,221,350,351,352,0,0,0,0,0,0,0,0,0,0}},   // Poison III
    {223,6,0x003F,{220,221,222,350,351,352,0,0,0,0,0,0,0,0,0}},   // Poison IV
    {224,7,0x007F,{220,221,222,223,350,351,352,0,0,0,0,0,0,0,0}},   // Poison V
    {230,1,0x0001,{23,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Bio
    {231,3,0x0007,{23,24,230,0,0,0,0,0,0,0,0,0,0,0,0}},   // Bio II
    {232,5,0x001F,{23,24,25,230,231,0,0,0,0,0,0,0,0,0,0}},   // Bio III
    {233,6,0x003F,{23,24,25,230,231,232,0,0,0,0,0,0,0,0,0}},   // Bio IV
    {234,7,0x007F,{23,24,25,230,231,232,233,0,0,0,0,0,0,0,0}},   // Bio V
    {235,1,0x0000,{236,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Burn
    {236,1,0x0000,{237,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Frost
    {237,1,0x0000,{238,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Choke
    {238,1,0x0000,{239,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Rasp
    {239,1,0x0000,{240,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Shock
    {240,1,0x0000,{235,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Drown
    {259,2,0x0003,{253,273,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Sleep II
    {274,2,0x0003,{253,273,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Sleepga II
    {276,4,0x000F,{254,347,348,349,0,0,0,0,0,0,0,0,0,0,0}},   // Blind II
    {312,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enfire II
    {313,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enblizzard II
    {314,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enaero II
    {315,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enstone II
    {316,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enthunder II
    {317,12,0x003F,{100,101,102,103,104,105,312,313,314,315,316,317,0,0,0}},   // Enwater II
    {342,1,0x0001,{341,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Jubaku: Ni
    {343,2,0x0003,{341,342,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Jubaku: San
    {345,1,0x0001,{344,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Hojo: Ni
    {346,2,0x0003,{344,345,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Hojo: San
    {348,1,0x0001,{347,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Kurayami: Ni
    {349,2,0x0003,{347,348,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Kurayami: San
    {351,1,0x0001,{350,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Dokumori: Ni
    {352,2,0x0003,{350,351,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Dokumori: San
    {369,1,0x0001,{368,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Foe Requiem II
    {370,2,0x0003,{368,369,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Foe Requiem III
    {371,3,0x0007,{368,369,370,0,0,0,0,0,0,0,0,0,0,0,0}},   // Foe Requiem IV
    {372,4,0x000F,{368,369,370,371,0,0,0,0,0,0,0,0,0,0,0}},   // Foe Requiem V
    {373,5,0x001F,{368,369,370,371,372,0,0,0,0,0,0,0,0,0,0}},   // Foe Requiem VI
    {374,6,0x003F,{368,369,370,371,372,373,0,0,0,0,0,0,0,0,0}},   // Foe Requiem VII
    {375,7,0x007F,{368,369,370,371,372,373,374,0,0,0,0,0,0,0,0}},   // Foe Requiem VIII
    {377,2,0x0003,{376,463,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Horde Lullaby II
    {422,1,0x0001,{421,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Carnage Elegy
    {423,2,0x0003,{421,422,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Massacre Elegy
    {465,2,0x0000,{465,467,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Chocobo Mazurka
    {467,2,0x0000,{465,467,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Raptor Mazurka
    {471,2,0x0003,{376,463,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Foe Lullaby II
    {511,3,0x0003,{57,845,846,0,0,0,0,0,0,0,0,0,0,0,0}},   // Haste II
    {728,1,0x0001,{717,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Tenebral Crush
    {740,2,0x0003,{717,728,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Tourbillion
    {842,1,0x0001,{841,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Distract II
    {844,1,0x0001,{843,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Frazzle II
    {845,1,0x0000,{57,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Flurry
    {846,3,0x0005,{57,511,845,0,0,0,0,0,0,0,0,0,0,0,0}},   // Flurry II
    {857,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Sandstorm II
    {858,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Rainstorm II
    {859,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Windstorm II
    {860,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Firestorm II
    {861,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Hailstorm II
    {862,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Thunderstorm II
    {863,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Voidstorm II
    {864,8,0x0000,{857,858,859,860,861,862,863,864,0,0,0,0,0,0,0}},   // Aurorastorm II
    {871,15,0x00FF,{454,455,456,457,458,459,460,461,872,873,874,875,876,877,878}},   // Fire Threnody II
    {872,15,0x00FF,{454,455,456,457,458,459,460,461,871,873,874,875,876,877,878}},   // Ice Threnody II
    {873,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,874,875,876,877,878}},   // Wind Threnody II
    {874,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,873,875,876,877,878}},   // Earth Threnody II
    {875,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,873,874,876,877,878}},   // Ltng. Threnody II
    {876,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,873,874,875,877,878}},   // Water Threnody II
    {877,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,873,874,875,876,878}},   // Light Threnody II
    {878,15,0x00FF,{454,455,456,457,458,459,460,461,871,872,873,874,875,876,877}},   // Dark Threnody II
    {882,2,0x0003,{841,842,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Distract III
    {883,2,0x0003,{843,844,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Frazzle III
    {884,1,0x0001,{286,0,0,0,0,0,0,0,0,0,0,0,0,0,0}},   // Addle II
    {885,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Geohelix II
    {886,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Hydrohelix II
    {887,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Anemohelix II
    {888,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Pyrohelix II
    {889,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Cryohelix II
    {890,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Ionohelix II
    {891,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Noctohelix II
    {892,8,0x00FF,{278,279,280,281,282,283,284,285,0,0,0,0,0,0,0}},   // Luminohelix II
};
static const int SPELL_OVERWRITES_N = (int)(sizeof(SPELL_OVERWRITES)/sizeof(SPELL_OVERWRITES[0]));
// binary search (sorted by spell id). 0 = this spell overwrites nothing.
inline const SpellOverwrite* spell_overwrites(unsigned spell) {
    int lo = 0, hi = SPELL_OVERWRITES_N - 1;
    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = SPELL_OVERWRITES[mid].spell;
        if (s == spell) return &SPELL_OVERWRITES[mid]; if (s < spell) lo = mid + 1; else hi = mid - 1; }
    return 0;
}
// AoE (-ga) form -> its single-target twin. res lists no `overwrites` for them, but the game treats them as
// the same spell ("Dia II overrides Diaga, but not the other way around"), so both sides of a comparison are
// canonicalised through this first. Without it a Diaga I silently downgraded a Dia II (same status 134).
struct SpellAlias { unsigned short spell, same; };
static const SpellAlias OW_ALIAS[] = {
    {33,23},   // Diaga -> Dia
    {34,24},   // Diaga II -> Dia II
    {35,25},   // Diaga III -> Dia III
    {36,26},   // Diaga IV -> Dia IV
    {37,27},   // Diaga V -> Dia V
    {225,220},   // Poisonga -> Poison
    {226,221},   // Poisonga II -> Poison II
    {227,222},   // Poisonga III -> Poison III
    {228,223},   // Poisonga IV -> Poison IV
    {229,224},   // Poisonga V -> Poison V
    {273,253},   // Sleepga -> Sleep
    {274,259},   // Sleepga II -> Sleep II
    {357,56},   // Slowga -> Slow
    {358,57},   // Hastega -> Haste
    {361,254},   // Blindga -> Blind
    {363,253},   // Sleepga -> Sleep
    {364,259},   // Sleepga II -> Sleep II
};
static const int OW_ALIAS_N = (int)(sizeof(OW_ALIAS)/sizeof(OW_ALIAS[0]));
inline unsigned ow_canonical(unsigned spell) {
    for (int i = 0; i < OW_ALIAS_N; ++i) if (OW_ALIAS[i].spell == spell) return OW_ALIAS[i].same;
    return spell;
}
// does spell `a` overwrite spell `b` ? (false when they resolve to the SAME spell : a recast, or the AoE form
// of what is already up, is a refresh -- not an overwrite)
inline const SpellOverwrite* spell_ow_edge(unsigned a, unsigned b, int* idx) {
    a = ow_canonical(a); b = ow_canonical(b);
    if (!a || !b || a == b) return 0;
    const SpellOverwrite* o = spell_overwrites(a);
    if (!o) return 0;
    for (int i = 0; i < o->n; ++i) if (o->list[i] == b) { if (idx) *idx = i; return o; }
    return 0;
}
// does `a` STRICTLY OUTRANK `b` -- a real strength order, not merely "these two cannot coexist" ?
// This is the only form that may refuse a cast. A cyclic pair (Burn/Frost/.../Drown, the mutual Threnody II)
// answers false BOTH ways : each replaces the other in game, so neither may ever be called the stronger.
inline bool spell_outranks_spell(unsigned a, unsigned b) {
    int i = -1; const SpellOverwrite* o = spell_ow_edge(a, b, &i);
    return o && i >= 0 && ((o->strict >> i) & 1) != 0;
}
inline bool spell_overwrites_spell(unsigned a, unsigned b) { return spell_ow_edge(a, b, 0) != 0; }
} // namespace aio
