// regen_dur_gen.h -- GENERATED by scripts/gen_regen_dur.py from Windower res/item_descriptions.lua.
// Do NOT hand-edit ; regenerate. item id -> native '"Regen" (effect) duration +N' SECONDS (flat,
// Regen-only). Added to Regen's base BEFORE the enhancing-duration multiplier ; never affects other
// enhancing spells. Universal / future-proof. Included by regen_dur.h as REGEN_DUR_SEC.
#pragma once
namespace aio {
static const RegenDurItem REGEN_DUR_SEC[] = {
    {21175,12},{23062,24},{23221,24},{23243,21},{23397,27},{23556,26},{23578,24},{23917,27},{24032,24},
    {26265,15},{26364,15},{26894,12},{27056,20},{27057,22},{27706,21},{28113,18},
};
static const int REGEN_DUR_SEC_N = (int)(sizeof(REGEN_DUR_SEC)/sizeof(REGEN_DUR_SEC[0]));
} // namespace aio
