// song_dur_gen.h -- GENERATED by scripts/gen_song_dur.py. Do NOT hand-edit ; regenerate.
// Built from Windower res/item_descriptions.lua (+ the reference sheet for the items whose text is
// qualitative). Song POTENCY is duration: +10% per point, per the BG-Wiki Category:Song rule --
//   m1 = 1 + SUM(explicit +N%) + SUM(10% per 'All songs +N') + SUM(10% per '"<Song>"+N' of THIS
//            family) + 0.05 BRD JP gift.        Troubadour's x2 multiplies the TOTAL, not m1.
// `flat` already folds 'All songs +N' in, since that applies to every song exactly like an explicit %.
// 131 items carry song duration ; 82 of them through a family-specific potency.
#pragma once
namespace aio {

struct SongDurFam { unsigned char family, pct; };
struct SongDurItem { unsigned short id; unsigned char flat; SongDurFam fam[2]; };
static const SongDurItem SONG_DUR[] = {
    {11073,   0,{{5,10},{0,0}}},   // Aoidos' Calot +2
    {11093,  10,{{4,10},{0,0}}},   // Aoidos' Hngrln. +2
    {11113,   0,{{8,10},{0,0}}},   // Ad. Mnchtte. +2
    {11133,   0,{{2,10},{0,0}}},   // Aoidos' Rhing. +2
    {11153,   0,{{14,10},{0,0}}},   // Aoidos' Cothrn. +2
    {11193,   5,{{0,0},{0,0}}},   // Aoidos' Hngrln. +1
    {11618,  10,{{0,0},{0,0}}},   // Aoidos' Matinee
    {17344,   0,{{4,10},{0,0}}},   // Cornette
    {17348,   0,{{5,10},{0,0}}},   // Traversiere
    {17349,   0,{{8,20},{0,0}}},   // Faerie Piccolo
    {17350,   0,{{6,10},{0,0}}},   // Angel's Flute
    {17351,   0,{{7,10},{0,0}}},   // Gemshorn
    {17354,   0,{{3,10},{0,0}}},   // Harp
    {17355,   0,{{9,10},{0,0}}},   // Rose Harp
    {17357,   0,{{1,10},{0,0}}},   // Ebony Harp
    {17358,   0,{{1,30},{0,0}}},   // Oneiros Harp
    {17359,   0,{{9,10},{0,0}}},   // Mythic Harp
    {17360,   0,{{8,30},{9,30}}},   // Langeleik
    {17361,   0,{{10,10},{0,0}}},   // Crumhorn
    {17363,   0,{{11,30},{14,10}}},   // Mass Chalemie
    {17367,   0,{{8,10},{0,0}}},   // Ryl.Spr. Horn
    {17369,   0,{{4,20},{0,0}}},   // Cornette +1
    {17370,   0,{{7,20},{0,0}}},   // Gemshorn +1
    {17373,   0,{{3,10},{0,0}}},   // Maple Harp +1
    {17374,   0,{{3,20},{0,0}}},   // Harp +1
    {17375,   0,{{5,20},{0,0}}},   // Traversiere +1
    {17376,   0,{{9,20},{0,0}}},   // Rose Harp +1
    {17377,   0,{{10,20},{0,0}}},   // Crumhorn +1
    {17378,   0,{{6,20},{0,0}}},   // Angel's Flute +1
    {17833,   0,{{1,20},{0,0}}},   // Ebony Harp +1
    {17834,   0,{{9,20},{0,0}}},   // Mythic Harp +1
    {17835,   0,{{8,10},{0,0}}},   // San d'Orian Horn
    {17836,   0,{{8,10},{0,0}}},   // Kingdom Horn
    {17838,   0,{{12,20},{0,0}}},   // Harlequin's Horn
    {17840,   0,{{11,20},{0,0}}},   // Angel Lyre
    {17845,   0,{{5,20},{0,0}}},   // Traversiere +2
    {17846,   0,{{4,20},{0,0}}},   // Cornette +2
    {17847,   0,{{10,20},{0,0}}},   // Crumhorn +2
    {17848,   0,{{1,20},{0,0}}},   // Ebony Harp +2
    {17849,   0,{{7,10},{0,0}}},   // Hellish Bugle
    {17850,   0,{{7,20},{0,0}}},   // Hellish Bugle +1
    {17851,   0,{{2,10},{0,0}}},   // Storm Fife
    {17853,   0,{{8,20},{0,0}}},   // Iron Ram Horn
    {17856,   0,{{3,30},{0,0}}},   // Syrinx
    {18341,  20,{{0,0},{0,0}}},   // Millennium Horn
    {18342,  20,{{0,0},{0,0}}},   // Gjallarhorn
    {18571,  30,{{0,0},{0,0}}},   // Daurdabla
    {18572,  40,{{0,0},{0,0}}},   // Gjallarhorn
    {18575,  25,{{0,0},{0,0}}},   // Daurdabla
    {18576,  30,{{0,0},{0,0}}},   // Daurdabla
    {18577,  20,{{0,0},{0,0}}},   // Gjallarhorn
    {18578,  20,{{0,0},{0,0}}},   // Gjallarhorn
    {18579,  30,{{0,0},{0,0}}},   // Gjallarhorn
    {18580,  30,{{0,0},{0,0}}},   // Gjallarhorn
    {18831,   0,{{2,10},{0,0}}},   // Crooner's Cithara
    {18832,   0,{{4,30},{0,0}}},   // Apollo's Flute
    {18833,   0,{{5,30},{6,30}}},   // Cantabank's Horn
    {18834,   0,{{7,30},{12,30}}},   // Vihuela
    {18839,  30,{{0,0},{0,0}}},   // Daurdabla
    {18840,  40,{{0,0},{0,0}}},   // Gjallarhorn
    {18980,  10,{{0,0},{0,0}}},   // Carnwenhan
    {19000,  10,{{0,0},{0,0}}},   // Carnwenhan
    {19069,  20,{{0,0},{0,0}}},   // Carnwenhan
    {19089,  30,{{0,0},{0,0}}},   // Carnwenhan
    {19621,  40,{{0,0},{0,0}}},   // Carnwenhan
    {19719,  40,{{0,0},{0,0}}},   // Carnwenhan
    {19828,  50,{{0,0},{0,0}}},   // Carnwenhan
    {19957,  50,{{0,0},{0,0}}},   // Carnwenhan
    {20561,  50,{{0,0},{0,0}}},   // Carnwenhan
    {20562,  50,{{0,0},{0,0}}},   // Carnwenhan
    {20586,  50,{{0,0},{0,0}}},   // Carnwenhan
    {20599,   5,{{0,0},{0,0}}},   // Kali
    {20629,   5,{{0,0},{0,0}}},   // Legato Dagger
    {21398,  50,{{0,0},{0,0}}},   // Marsyas
    {21399,   0,{{10,20},{0,0}}},   // Nibiru Harp
    {21400,  10,{{0,0},{0,0}}},   // Blurred Harp
    {21401,  20,{{2,20},{0,0}}},   // Blurred Harp +1
    {21404,  10,{{0,0},{0,0}}},   // Linos
    {21405,  20,{{0,0},{0,0}}},   // Eminent Flute
    {21406,  40,{{0,0},{0,0}}},   // Homestead Flute
    {21409,  20,{{0,0},{0,0}}},   // Forefront Flute
    {22249,  30,{{0,0},{0,0}}},   // Miracle Cheer
    {22305,  20,{{0,0},{0,0}}},   // Loughnashade
    {22306,  30,{{0,0},{0,0}}},   // Loughnashade
    {22307,  40,{{0,0},{0,0}}},   // Loughnashade
    {23049,   0,{{1,10},{0,0}}},   // Brioso Roundlet +2
    {23094,   0,{{5,10},{0,0}}},   // Fili Calot +2
    {23161,  13,{{4,10},{0,0}}},   // Fili Hongreline +2
    {23228,   0,{{8,10},{0,0}}},   // Fili Manchettes +2
    {23295,   0,{{2,10},{0,0}}},   // Fili Rhingrave +2
    {23317,  13,{{0,0},{0,0}}},   // Brioso Slippers +2
    {23362,   0,{{14,10},{0,0}}},   // Fili Cothurnes +2
    {23384,   0,{{1,20},{0,0}}},   // Brioso Roundlet +3
    {23429,   0,{{5,10},{0,0}}},   // Fili Calot +3
    {23496,  14,{{4,10},{0,0}}},   // Fili Hongreline +3
    {23563,   0,{{8,10},{0,0}}},   // Fili Manchettes +3
    {23630,   0,{{2,10},{0,0}}},   // Fili Rhingrave +3
    {23652,  15,{{0,0},{0,0}}},   // Brioso Slippers +3
    {23697,   0,{{14,10},{0,0}}},   // Fili Cothurnes +3
    {23904,   0,{{1,20},{0,0}}},   // Brioso Roundlet +4
    {24084,  15,{{0,0},{0,0}}},   // Brioso Slippers +4
    {25561,   0,{{9,10},{0,0}}},   // Mousai Turban
    {25562,   0,{{9,20},{0,0}}},   // Mousai Turban +1
    {25865,  12,{{0,0},{0,0}}},   // Inyanga Shalwar
    {25866,  15,{{0,0},{0,0}}},   // Inyanga Shalwar +1
    {25882,  17,{{0,0},{0,0}}},   // Inyanga Shalwar +2
    {25901,   0,{{3,10},{0,0}}},   // Mousai Seraweels
    {25902,   0,{{3,20},{0,0}}},   // Mou. Seraweels +1
    {25968,   0,{{7,10},{0,0}}},   // Mousai Crackows
    {25969,   0,{{7,20},{0,0}}},   // Mou. Crackows +1
    {25988,   0,{{10,10},{0,0}}},   // Mousai Gages
    {25989,   0,{{10,20},{0,0}}},   // Mousai Gages +1
    {26031,  10,{{0,0},{0,0}}},   // Brioso Whistle
    {26032,  20,{{0,0},{0,0}}},   // Moonbow Whistle
    {26033,  30,{{0,0},{0,0}}},   // Mnbw. Whistle +1
    {26255,   0,{{5,10},{6,10}}},   // Intarabus's Cape
    {26758,   0,{{5,10},{0,0}}},   // Fili Calot
    {26759,   0,{{5,10},{0,0}}},   // Fili Calot +1
    {26916,  11,{{4,10},{0,0}}},   // Fili Hongreline
    {26917,  12,{{4,10},{0,0}}},   // Fili Hongreline +1
    {27070,   0,{{8,10},{0,0}}},   // Fili Manchettes
    {27071,   0,{{8,10},{0,0}}},   // Fili Manchettes +1
    {27255,   0,{{2,10},{0,0}}},   // Fili Rhingrave
    {27256,   0,{{2,10},{0,0}}},   // Fili Rhingrave +1
    {27429,   0,{{14,10},{0,0}}},   // Fili Cothurnes
    {27430,   0,{{14,10},{0,0}}},   // Fili Cothurnes +1
    {27672,   0,{{1,10},{0,0}}},   // Brioso Roundlet
    {27693,   0,{{1,10},{0,0}}},   // Brioso Roundlet +1
    {28074,  10,{{0,0},{0,0}}},   // Mdk. Shalwar +1
    {28232,  10,{{0,0},{0,0}}},   // Brioso Slippers
    {28253,  11,{{0,0},{0,0}}},   // Brioso Slippers +1
};
static const int SONG_DUR_N = (int)(sizeof(SONG_DUR) / sizeof(SONG_DUR[0]));

} // namespace aio
