#!/usr/bin/env python3
# gen_song_family.py -- generate src/model/song_family_gen.h from Windower res/spells.lua.
# Maps each BRD song (skill 40) to its Timers song-family id (param_2), by the family word in its English name.
# Used by the BRD song-duration model to apply per-family gear bonuses + the Soul Voice/Marcato m3 (families
# 11 Hymnus / 12 Mazurka / 14 Scherzo). Family ids match Timers.dll (RE'd) : 1 Paeon .. 15 Operetta/misc.
#
#   python scripts/gen_song_family.py [path-to-res/spells.lua] > src/model/song_family_gen.h
#   (no argument : res\ from $WINDOWER_RES, else the dev install -- genpaths.py)
import os, re, sys
import genpaths
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(genpaths.res_dir(), "spells.lua")

FAM = {  # family word (in the song's English name) -> Timers family id
    "Paeon":1, "Ballad":2, "Minne":3, "Minuet":4, "Madrigal":5, "Prelude":6,
    "Mambo":7, "March":8, "Etude":9, "Carol":10, "Hymnus":11, "Mazurka":12,
    "Sirvente":13, "Dirge":13, "Scherzo":14,
    "Operetta":15, "Capriccio":15, "Aubade":15, "Fantasia":15, "Round":15, "Pastoral":15,
}
rows = []
for ln in open(src, encoding="utf-8"):
    if "skill=40" not in ln:
        continue
    m = re.search(r'\[(\d+)\]\s*=\s*\{id=\d+,en="([^"]+)"', ln)
    if not m:
        continue
    sid, en = int(m.group(1)), m.group(2)
    fam = 0
    for word, fid in FAM.items():
        if word in en:
            fam = fid; break
    if fam:
        rows.append((sid, fam, en))

rows.sort()
out = []
out.append("// song_family_gen.h -- GENERATED by scripts/gen_song_family.py from Windower res/spells.lua.")
out.append("// BRD song spell id -> Timers song-family id (1 Paeon .. 15 Operetta ; 11 Hymnus 12 Mazurka 14 Scherzo).")
out.append("// Do NOT hand-edit ; regenerate. Used by song_dur.h for per-family gear bonuses + the m3 term.")
out.append("#pragma once")
out.append("namespace aio {")
out.append("struct SongFamily { unsigned short spell; unsigned char family; };")
out.append("static const SongFamily SONG_FAMILY[] = {")
line = "    "
for (s, f, _en) in rows:
    tok = "{%d,%d}," % (s, f)
    if len(line) + len(tok) > 108:
        out.append(line); line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int SONG_FAMILY_N = (int)(sizeof(SONG_FAMILY)/sizeof(SONG_FAMILY[0]));")
out.append("// spell id -> family (0 = not a family-mapped buff song).")
out.append("inline int song_family(unsigned spell) {")
out.append("    int lo = 0, hi = SONG_FAMILY_N - 1;")
out.append("    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = SONG_FAMILY[mid].spell;")
out.append("        if (s == spell) return SONG_FAMILY[mid].family; if (s < spell) lo = mid + 1; else hi = mid - 1; }")
out.append("    return 0;")
out.append("}")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d song->family rows\n" % len(rows))
