#!/usr/bin/env python3
# gen_enh_dur.py -- generate src/model/enh_dur_listed_gen.h from Windower res/item_descriptions.lua.
# Parses every item's in-game description for a NATIVE "Enhancing magic duration +N%" (or "Enhancing Magic
# effect duration +N%", or a negative like Sroda Necklace -50%) and emits an item id -> percent table.
#
# This is the game's own item text (extracted by Windower) -> UNIVERSAL & future-proof : any current or future
# item with a native enhancing-duration line is covered, no hand-maintained list. Augment "Enh. Mag. eff. dur."
# lives in the item's extdata (decoded live in enh_dur.h), NOT here.
#
#   python scripts/gen_enh_dur.py [path-to-res/item_descriptions.lua] > src/model/enh_dur_listed_gen.h
#   (no argument : res\ from $WINDOWER_RES, else the dev install -- genpaths.py)
import os, re, sys
import genpaths

src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(genpaths.res_dir(), "item_descriptions.lua")

# match (CASE-INSENSITIVE : some items write "Duration" capitalised, e.g. Sroda Necklace -50%) :
#   Enhancing magic duration +10%  /  Enhancing Magic effect duration +20%  /  ...duration+18%  /  ...Duration -50%
DUR = re.compile(r"Enhancing\s+magic\s+(?:effect\s+)?duration\s*([+-]\d+)\s*%", re.IGNORECASE)
LINE = re.compile(r"\[(\d+)\]\s*=\s*\{id=\d+,en=\"((?:[^\"\\]|\\.)*)\"")

rows = []
for ln in open(src, encoding="utf-8"):
    m = LINE.search(ln)
    if not m:
        continue
    iid = int(m.group(1)); en = m.group(2)
    d = DUR.search(en)
    if not d:
        continue
    pct = int(d.group(1))
    if pct == 0:
        continue
    rows.append((iid, pct))

rows.sort()
out = []
out.append("// enh_dur_listed_gen.h -- GENERATED by scripts/gen_enh_dur.py from Windower res/item_descriptions.lua.")
out.append("// Do NOT hand-edit ; regenerate. item id -> NATIVE 'Enhancing magic duration +N%%' (from the item's")
out.append("// in-game description ; negative allowed, e.g. Sroda Necklace -50). Universal / future-proof : covers")
out.append("// every item in the game with a native enhancing-duration line. Augment duration is decoded from")
out.append("// extdata separately (enh_dur.h). Included by enh_dur.h as the ENH_DUR_LISTED table.")
out.append("#pragma once")
out.append("namespace aio {")
out.append("static const EnhDurItem ENH_DUR_LISTED[] = {")
line = "    "
for (i, p) in rows:
    tok = "{%d,%d}," % (i, p)
    if len(line) + len(tok) > 108:
        out.append(line); line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int ENH_DUR_LISTED_N = (int)(sizeof(ENH_DUR_LISTED)/sizeof(ENH_DUR_LISTED[0]));")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d native enhancing-duration items from %s\n" % (len(rows), src))
