#!/usr/bin/env python3
# gen_action_status.py -- action id -> the STATUS it applies, PLUS two classifiers for the Timers box :
#   (1) SPELL_STATUS / ABIL_STATUS : id -> status, for buff-CASTER attribution (who put a buff on you).
#   (2) STATUS_SPELL_JOBS : status -> bitmask of jobs that can SELF-produce it (self/party-target buff spells only),
#       so the "self-cast only" filter can hide a buff of UNKNOWN caster that your current job could never cast
#       (a Trust's Protectra / Geo-Haste on a Bard) while keeping ones it could (your own songs).
#   (3) DEBUFF_STATUS : status ids that are ENFEEBLES (never belong in a buff-duration list) : the base 0..31
#       natural debuffs + elemental DoTs + every status an ENEMY-targeting spell applies, minus anything that is
#       ALSO a real self/party buff. Lets the box drop Blind / Poison / Slow / Dia / Bio that leak via 0x063.
# Source : res/{spells,job_abilities}.lua. Output : src/model/action_status_gen.h.
import re, os
import genpaths
# res lives beside the Windower install : $WINDOWER_RES, else the dev install (genpaths.py).
RES = genpaths.res_dir()
if not os.path.isfile(os.path.join(RES, 'spells.lua')):
    raise SystemExit('res/spells.lua not found in %s -- set WINDOWER_RES to your Windower res folder' % RES)
OUT = genpaths.out_path('action_status_gen.h')

ENEMY = 32   # windower target bitflag : Self=1 Player=2 Party=4 Ally=8 NPC=16 Enemy=32

def field(line, name):
    m = re.search(r'(?<![a-z_])%s=(\d+)' % name, line)
    return int(m.group(1)) if m else None

def build_ids(path):                       # id -> status (rows that HAVE a status), for attribution
    m = {}
    for line in open(path, encoding='utf-8'):
        i, s = field(line, 'id'), field(line, 'status')
        if i is not None and s and s > 0:
            m[i] = s
    return sorted(m.items())

spell_path = os.path.join(RES, 'spells.lua')
abil_path  = os.path.join(RES, 'job_abilities.lua')
sp = build_ids(spell_path)
ab = build_ids(abil_path)

# SP-ability buff statuses : abilities whose recast_id is 0 (SP1) or 254 (SP2) and that grant a status. Their buff
# durations get the "last minute" alert in the Timers box (blink hard -> re-buff before it drops).
sp_status = set()
for line in open(abil_path, encoding='utf-8'):
    rc, st = field(line, 'recast_id'), field(line, 'status')
    if st and st > 0 and rc in (0, 254):
        sp_status.add(st)
sp_status = sorted(sp_status)

# --- per-spell scan for the job-mask + buff/debuff split ---
status_jobs = {}          # status -> jobmask (self/party buff spells)
buff_status = set()       # statuses granted by a self/party (non-enemy) spell
enemy_status = set()      # statuses applied by an enemy-targeting spell
for line in open(spell_path, encoding='utf-8'):
    st = field(line, 'status')
    if not st or st <= 0:
        continue
    tg = field(line, 'targets') or 0
    if tg & ENEMY:
        enemy_status.add(st)
        continue
    buff_status.add(st)
    lv = re.search(r'levels=\{([^}]*)\}', line)
    if lv:
        mask = 0
        for jm in re.finditer(r'\[(\d+)\]=', lv.group(1)):
            j = int(jm.group(1))
            if 1 <= j <= 31:
                mask |= (1 << (j - 1))
        status_jobs[st] = status_jobs.get(st, 0) | mask
# abilities that grant a status are always self/party buffs (rolls, Cor rolls, etc.)
abil_buff_status = {s for _, s in ab}

# debuff set : natural 0..31 + elemental DoTs 128..133 + enemy-only statuses, MINUS anything that is a real buff.
base_debuff = set(range(0, 32)) | set(range(128, 134))
debuffs = sorted((base_debuff | enemy_status) - buff_status - abil_buff_status)
sjobs = sorted(status_jobs.items())

def emit_pairs(name, rows, ty='ActStatus'):
    out = ['static const %s %s[] = {' % (ty, name)]
    out += ['    {%d,%d},' % (a, b) for a, b in rows]
    out += ['};', 'static const int %s_N = %d;' % (name, len(rows))]
    return out

L = ['// action_status_gen.h -- GENERATED by scripts/gen_action_status.py (res/spells.lua + res/job_abilities.lua).',
     '// action id -> status effect id + job-mask / debuff classifiers for the Timers self-cast filter.',
     '#pragma once', 'namespace aio {', 'struct ActStatus { unsigned short id, status; };',
     'struct StatusJobs { unsigned short status; unsigned mask; };']
L += emit_pairs('SPELL_STATUS', sp)
L += emit_pairs('ABIL_STATUS', ab)
L += ['static const StatusJobs STATUS_SPELL_JOBS[] = {']
L += ['    {%d,0x%Xu},' % (s, m) for s, m in sjobs]
L += ['};', 'static const int STATUS_SPELL_JOBS_N = %d;' % len(sjobs)]
L += ['static const unsigned short DEBUFF_STATUS[] = {']
L += ['    ' + ', '.join(str(d) for d in debuffs) + (',' if debuffs else '')]
L += ['};', 'static const int DEBUFF_STATUS_N = %d;' % len(debuffs)]
L += ['static const unsigned short SP_BUFF_STATUS[] = {']
L += ['    ' + ', '.join(str(d) for d in sp_status) + (',' if sp_status else '')]
L += ['};', 'static const int SP_BUFF_STATUS_N = %d;' % len(sp_status)]
L += ['inline unsigned act_status_lookup(const ActStatus* a, int n, unsigned id) {',
      '    int lo = 0, hi = n - 1;',
      '    while (lo <= hi) { int m = (lo + hi) >> 1; unsigned v = a[m].id;',
      '        if (v == id) return a[m].status; if (v < id) lo = m + 1; else hi = m - 1; }',
      '    return 0; }',
      'inline unsigned spell_buff_status(unsigned id) { return act_status_lookup(SPELL_STATUS, SPELL_STATUS_N, id); }',
      'inline unsigned abil_buff_status(unsigned id)  { return act_status_lookup(ABIL_STATUS,  ABIL_STATUS_N,  id); }',
      'inline unsigned status_spell_jobs(unsigned status) {',
      '    int lo = 0, hi = STATUS_SPELL_JOBS_N - 1;',
      '    while (lo <= hi) { int m = (lo + hi) >> 1; unsigned v = STATUS_SPELL_JOBS[m].status;',
      '        if (v == status) return STATUS_SPELL_JOBS[m].mask; if (v < status) lo = m + 1; else hi = m - 1; }',
      '    return 0; }',
      'inline bool is_debuff_status(unsigned status) {',
      '    for (int i = 0; i < DEBUFF_STATUS_N; ++i) if (DEBUFF_STATUS[i] == status) return true;',
      '    return false; }',
      'inline bool is_sp_buff_status(unsigned status) {',
      '    for (int i = 0; i < SP_BUFF_STATUS_N; ++i) if (SP_BUFF_STATUS[i] == status) return true;',
      '    return false; }',
      '} // namespace aio']
open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('wrote %s : %d spells + %d abils, %d status-job rows, %d debuffs' % (OUT, len(sp), len(ab), len(sjobs), len(debuffs)))
