#!/usr/bin/env python3
# gen_tb_buffs.py -- generate src/model/tb_buff_gen.h from Windower's res/spells.lua.
# This is the SAME authoritative source the Windower Timers plugin uses : its buff timer
# `Base` == res/spells.lua `duration`, and the buff status == `status` (verified by RE of
# Timers.dll). We keep spells that grant a status, last a while, and can be cast on an ally
# (targets bitmask has Self/Party/Ally) -> the enhancing buffs you land on party members.
#
# Runtime detection (PartyState::on_action) fires only when YOU cast one of these on a real
# party/alliance member, so the table maps spell id -> { status effect, BASE duration sec }.
# NOTE: this is the BASE duration (no gear/merit/trait bonus) ; the caster's "Enhancing Magic
# Duration+" gear is applied separately at runtime (Timers reads it live from equipment).
#
#   python scripts/gen_tb_buffs.py [path-to-res/spells.lua] > src/model/tb_buff_gen.h
#   (no argument : res\ from $WINDOWER_RES, else the dev install -- genpaths.py)
import os, re, sys
import genpaths

src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(genpaths.res_dir(), "spells.lua")

# FFXI `targets` bitmask flags. A buff you can put on an ally must be castable on Self/Party/Ally.
T_SELF, T_PARTY, T_ALLY, T_ENEMY = 0x01, 0x04, 0x08, 0x20

def field(body, key):
    m = re.search(r"\b" + key + r"=(-?\d+)", body)
    return int(m.group(1)) if m else None

rows = []
line_re = re.compile(r"\[(\d+)\]\s*=\s*\{(.+)\}")
for ln in open(src, encoding="utf-8"):
    m = line_re.search(ln)
    if not m:
        continue
    sid = int(m.group(1)); body = m.group(2)
    dur = field(body, "duration"); status = field(body, "status"); targets = field(body, "targets")
    skill = field(body, "skill") or 0
    if not dur or dur <= 0:            # no lasting effect (Cure / nuke / instant)
        continue
    if not status or status <= 0:      # grants no tracked status icon
        continue
    if targets is None or (targets & (T_SELF | T_PARTY | T_ALLY)) == 0:
        continue                       # can't be cast on you or an ally (pure enemy debuff) -> skip
    if (targets & (T_PARTY | T_ALLY | T_SELF)) and (targets & T_ENEMY) and not (targets & (T_PARTY | T_ALLY)):
        continue                       # enemy-only + self (defensive spells rare) -- keep simple
    rows.append((sid, status, dur, skill))

rows.sort()
out = []
out.append("// tb_buff_gen.h -- GENERATED by scripts/gen_tb_buffs.py from Windower res/spells.lua.")
out.append("// Do NOT hand-edit ; regenerate. spell id -> { status effect id, BASE duration seconds, skill }.")
out.append("// Same source & values the Windower Timers plugin uses (its Base == res/spells.lua duration,")
out.append("// verified by RE of Timers.dll). Used by PartyState::on_action to time a BUFF you cast on an")
out.append("// ally. BASE only -- the caster's Enhancing-Duration gear + Composure are applied at runtime.")
out.append("// skill : res/spells.lua skill id (34 = Enhancing Magic -> eligible for the Composure x3 bonus).")
out.append("#pragma once")
out.append("namespace aio {")
out.append("struct SpellBuff { unsigned short spell, effect, durSec, skill; };")
out.append("static const SpellBuff TB_BUFFS[] = {")
line = "    "
for (s, e, d, sk) in rows:
    tok = "{%d,%d,%d,%d}," % (s, e, d, sk)
    if len(line) + len(tok) > 110:
        out.append(line); line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int TB_BUFFS_N = (int)(sizeof(TB_BUFFS)/sizeof(TB_BUFFS[0]));")
out.append("// binary search (TB_BUFFS is sorted by spell id). Returns 0 if the spell grants no tracked buff.")
out.append("inline const SpellBuff* spell_buff(unsigned spell) {")
out.append("    int lo = 0, hi = TB_BUFFS_N - 1;")
out.append("    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = TB_BUFFS[mid].spell;")
out.append("        if (s == spell) return &TB_BUFFS[mid]; if (s < spell) lo = mid + 1; else hi = mid - 1; }")
out.append("    return 0;")
out.append("}")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d buff-spell rows from %s\n" % (len(rows), src))
