#!/usr/bin/env python3
# gen_keyitems.py -- generate src/model/keyitems_gen.h from Windower's res/key_items.lua.
# The EmpyPop tracker needs id -> English name for key items (pop.type == 'key item'). res/key_items.lua is
# ~355 KB / ~3.2k entries ; we keep ONLY (id, en), sorted by id for a binary-search lookup.
# DO NOT hand-edit the output.
#
# Run:  python scripts/gen_keyitems.py             (from the repo root)
#       python scripts/gen_keyitems.py --res PATH  (explicit Windower res\ folder)
#
# res\ resolution (the dev repo lives OUTSIDE Windower, so it cannot be derived from __file__) :
#   1. --res PATH
#   2. $WINDOWER_RES (the name every generator shares, genpaths.py), then the legacy $AIOHUD_RES
#   3. the sibling res\ of WINDOWER_PLUGINS parsed out of deploy.local.bat (the repo's existing
#      untracked per-machine config -- same source deploy.bat uses)
#   4. the dev install, genpaths.DEV_RES
import re, os, sys
import genpaths

ROOT = genpaths.ROOT
OUT  = genpaths.out_path('keyitems_gen.h')


def res_dir():
    argv = sys.argv[1:]
    if '--res' in argv:
        return argv[argv.index('--res') + 1]
    for name in ('WINDOWER_RES', 'AIOHUD_RES'):
        if os.environ.get(name):
            return os.environ[name]
    # deploy.local.bat :  set "WINDOWER_PLUGINS=D:\Windower Tetsouo\plugins"  ->  ..\res
    local = os.path.join(ROOT, 'deploy.local.bat')
    if os.path.isfile(local):
        with open(local, 'r', encoding='utf-8', errors='replace') as f:
            m = re.search(r'set\s+"?WINDOWER_PLUGINS=([^"\r\n]+)"?', f.read(), re.I)
        if m:
            return os.path.join(os.path.dirname(m.group(1).rstrip('\\/')), 'res')
    return genpaths.DEV_RES


def cstr(s):
    # Work on UTF-8 BYTES so a multi-byte char keeps its exact bytes (the font's utf8_next decodes 2-byte
    # sequences to Latin-1). A hex escape (\xNN) is followed by "" so the compiler can't greedily merge it with
    # a following hex digit ("\x6a" + "1" would become \x6a1 = out of range) -- the empty string breaks parsing.
    out = []
    for by in s.encode('utf-8'):
        if   by == 0x5C: out.append('\\\\')          # backslash
        elif by == 0x22: out.append('\\"')           # quote
        elif 32 <= by < 127: out.append(chr(by))
        else: out.append('\\x%02x""' % by)           # non-ASCII / control byte : escape + string-break
    return ''.join(out)


def main():
    rd  = res_dir()
    lua = os.path.join(rd, 'key_items.lua')
    if not os.path.isfile(lua):
        sys.exit('[gen_keyitems] res\\key_items.lua not found at "%s"\n'
                 '                pass --res PATH, set WINDOWER_RES, or create deploy.local.bat' % lua)

    with open(lua, 'r', encoding='utf-8', errors='replace') as f:
        text = f.read()
    rows, seen = [], set()
    # [id] = {id=N,en="NAME",ja=...,category="..."}
    for m in re.finditer(r'\[(\d+)\]\s*=\s*\{[^}]*?\ben\s*=\s*"((?:[^"\\]|\\.)*)"', text):
        kid = int(m.group(1))
        if kid < 0 or kid > 65535 or kid in seen:
            continue
        name = m.group(2)
        if not name or name == '.':      # skip placeholders / blanks
            continue
        seen.add(kid)
        rows.append((kid, name))
    rows.sort(key=lambda r: r[0])
    if not rows:
        sys.exit('[gen_keyitems] parsed 0 entries from "%s" -- res format changed?' % lua)

    out = []
    out.append('// keyitems_gen.h -- GENERATED by scripts/gen_keyitems.py from Windower res/key_items.lua.')
    out.append('// id -> English key-item name (sorted by id, binary-searched). DO NOT hand-edit ; regenerate via the script.')
    out.append('// Names are lowercase as they ship in res/ ("dented Gigas shield") -- title-case at DRAW time, not here.')
    out.append('#pragma once')
    out.append('')
    out.append('namespace aio {')
    out.append('')
    out.append('struct KeyItemRow { unsigned short id; const char* en; };')
    out.append('static const KeyItemRow KEY_ITEMS[] = {')
    for (kid, name) in rows:
        out.append('    {%d, "%s"},' % (kid, cstr(name)))
    out.append('};')
    out.append('static const int KEY_ITEMS_N = %d;' % len(rows))
    out.append('')
    out.append('// English name for a key-item id, or 0 if unknown.')
    out.append('inline const char* key_item_name(unsigned id) {')
    out.append('    int lo = 0, hi = KEY_ITEMS_N - 1;')
    out.append('    while (lo <= hi) { const int mid = (lo + hi) >> 1; const unsigned m = KEY_ITEMS[mid].id;')
    out.append('        if (m == id) return KEY_ITEMS[mid].en; if (m < id) lo = mid + 1; else hi = mid - 1; }')
    out.append('    return 0;')
    out.append('}')
    out.append('')
    out.append('} // namespace aio')
    out.append('')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out))
    print('[gen_keyitems] %d key items (max id %d) -> %s' % (len(rows), rows[-1][0], OUT))


if __name__ == '__main__':
    main()
