#!/usr/bin/env python3
# gen_regen_dur.py -- generate src/model/regen_dur_gen.h from Windower res/item_descriptions.lua.
# Parses every item's in-game description for a native '"Regen" (effect) duration +N' line (FLAT SECONDS, no
# percent) and emits an item id -> seconds table. This is REGEN-SPECIFIC duration gear (Bolelabunga +12,
# Ebers/Orison Mitts, Theophany, Runeist Bandeau, Coeus, Lugh's Cape...) : it lengthens ONLY Regen, which is why
# it must be added to Regen's base (before the enhancing-duration multiplier) and never touches other enhancing
# spells. Mirrors gen_enh_dur.py -- game's own text -> UNIVERSAL & future-proof, no hand-maintained list.
#
#   python scripts/gen_regen_dur.py [path-to-res/item_descriptions.lua] > src/model/regen_dur_gen.h
#
# NOTE : items whose text is QUALITATIVE ("Increases \"Regen\" effect duration", no number) carry no value to
# extract and are skipped -- add those to a REGEN_DUR_EXTRA supplement in regen_dur.h if their seconds are known.
import re, sys

src = sys.argv[1] if len(sys.argv) > 1 else r"D:\Windower Tetsouo\res\item_descriptions.lua"

# '"Regen" duration +12' / '"Regen" effect duration +24' -- REQUIRE the word 'duration' (so '"Regen"+4' potency
# and '"Regen" potency +20%' never match) and a +N with NO trailing % (Regen duration is flat seconds).
# [\\"]* absorbs the escaped quotes the lua stores around the word (\"Regen\") ; REQUIRE 'duration' (so
# '\"Regen\"+4' potency and '\"Regen\" potency +20%' never match) and +N with NO trailing % (flat seconds).
# (?![\d%]) forbids a trailing digit OR % -> the digit run can't backtrack-truncate a hypothetical '+50%' into '+5'.
DUR  = re.compile(r'[\\"]*Regen[\\"]*\s+(?:effect\s+)?duration\s*\+(\d+)(?![\d%])', re.IGNORECASE)
LINE = re.compile(r'\[(\d+)\]\s*=\s*\{id=\d+,en="((?:[^"\\]|\\.)*)"')

rows = []
for ln in open(src, encoding="utf-8"):
    m = LINE.search(ln)
    if not m:
        continue
    iid = int(m.group(1)); en = m.group(2)
    d = DUR.search(en)
    if not d:
        continue
    sec = int(d.group(1))
    if sec == 0:
        continue
    rows.append((iid, sec))

rows.sort()
out = []
out.append("// regen_dur_gen.h -- GENERATED by scripts/gen_regen_dur.py from Windower res/item_descriptions.lua.")
out.append("// Do NOT hand-edit ; regenerate. item id -> native '\"Regen\" (effect) duration +N' SECONDS (flat,")
out.append("// Regen-only). Added to Regen's base BEFORE the enhancing-duration multiplier ; never affects other")
out.append("// enhancing spells. Universal / future-proof. Included by regen_dur.h as REGEN_DUR_SEC.")
out.append("#pragma once")
out.append("namespace aio {")
out.append("static const RegenDurItem REGEN_DUR_SEC[] = {")
line = "    "
for (i, s) in rows:
    tok = "{%d,%d}," % (i, s)
    if len(line) + len(tok) > 108:
        out.append(line); line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int REGEN_DUR_SEC_N = (int)(sizeof(REGEN_DUR_SEC)/sizeof(REGEN_DUR_SEC[0]));")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d Regen-duration items from %s\n" % (len(rows), src))
