#!/usr/bin/env python3
# gen_trusts.py -- GENERATE src/model/trusts_gen.h : the full Trust NAME -> job table.
#
# WHY : the party member array carries NO job for a trust, and is_trust()'s name fallback (used when the
#       entity SpawnType is unreadable -- e.g. ANOTHER player's trust, out of range) needs the trust's
#       ROSTER name. That name is the game's `party_name` (a truncated/compact form, e.g. "Babban",
#       "InvincibleShld"), NOT the pretty `en`. Hand-maintaining it drifted (2 names were the long form,
#       so those trusts were mis-classified as players). Generating from res/spells.lua keeps the names
#       authoritative and auto-adds any trust SE ships later.
#
# Source : res/spells.lua (type="Trust" -> party_name = the roster name) + curated jobs (parsed from the
#          EXISTING table so we don't lose the hand-reversed jobs ; spells.lua has no job for a trust).
# Output : src/model/trusts_gen.h.  Run : python scripts/gen_trusts.py

import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
def find_res():
    for c in [os.path.join(ROOT, '..', '..', 'res'), os.path.join(ROOT, 'res'), r'D:\Windower Tetsouo\res']:
        if os.path.isfile(os.path.join(c, 'spells.lua')): return c
    raise SystemExit('res/spells.lua not found')
RES = find_res()
OUT = os.path.join(ROOT, '..', 'src', 'model', 'trusts_gen.h')
# The curated jobs are re-read from THIS GENERATOR'S OWN OUTPUT, which is where the TRUSTS[] table lives.
# It used to point at party_state_roster.cpp, where the table was defined LONG AGO; after the move, the regex
# below matched nothing, `jobs` stayed empty, and a re-run silently rewrote all 106 rows as {"Name", 0, 0} --
# wiping every hand-reversed job and blanking the trust job badges. That is a generator that destroys its own
# data when you follow the instruction in CLAUDE.md to regenerate rather than hand-edit.
PREV = OUT

# --- curated jobs : parse the CURRENT table so hand-reversed jobs survive. Keyed by name AS WRITTEN there. ---
jobs = {}
if os.path.isfile(PREV):
    txt = open(PREV, encoding='utf-8', errors='ignore').read()
    m = re.search(r'TRUSTS\[\]\s*=\s*\{(.*?)\};', txt, re.S)
    if m:
        for name, mj, sj in re.findall(r'\{"([^"]+)"\s*,\s*("[^"]*"|0)\s*,\s*("[^"]*"|0)\}', m.group(1)):
            jobs[name] = (mj, sj)
# names that the OLD table wrote in the long form -> map to the game's party_name so the job carries over.
ALIAS = {'Babban': 'BabbanMheillea', 'InvincibleShld': 'InvincibleShield'}

# --- authoritative name list : every Trust spell's party_name (DEDUPED : variant summons share a party_name) ---
trusts = []   # (party_name, en) in spells.lua order, unique party_name
seen = set()
for line in open(os.path.join(RES, 'spells.lua'), encoding='utf-8'):
    if 'type="Trust"' not in line: continue
    pn = re.search(r'party_name="([^"]+)"', line); en = re.search(r'en="([^"]+)"', line)
    if pn and pn.group(1) not in seen:
        seen.add(pn.group(1)); trusts.append((pn.group(1), en.group(1) if en else pn.group(1)))

def job_of(pn):
    j = jobs.get(pn) or jobs.get(ALIAS.get(pn, ''))
    return j if j else ('0', '0')

L = ['// trusts_gen.h -- GENERATED by scripts/gen_trusts.py (res/spells.lua type="Trust" party_name + curated jobs).',
     '// Trust ROSTER name -> job. `name` is the game party_name (the field the roster reads). Jobs come from the',
     '// hand-reversed table (spells.lua carries none) ; a trust SE adds later appears here with job 0 (is_trust',
     '// still works by name ; only the job emblem degrades). DO NOT hand-edit -- rerun scripts/gen_trusts.py.',
     'struct TrustJob { const char* name; const char* mj; const char* sj; };',
     'static const TrustJob TRUSTS[] = {']
for pn, en in trusts:
    mj, sj = job_of(pn)
    L.append('    {"%s", %s, %s},' % (pn, mj, sj))
L.append('};')
have_jobs = sum(1 for pn, _ in trusts if job_of(pn) != ('0', '0'))
# REFUSE to write a table that knows FEWER jobs than the one already on disk. The jobs are hand-reversed and
# exist nowhere else -- no res file carries them -- so a regression here is unrecoverable data loss, and the run
# that caused it printed a cheerful success line ("106 trusts -> ..., 0 with a known job") that reads as normal
# because a brand-new trust legitimately has job 0. Loud and non-zero, or don't touch the file.
prev_known = sum(1 for v in jobs.values() if v != ('0', '0'))
if have_jobs < prev_known:
    sys.exit('gen_trusts: REFUSING to write -- would drop %d known job(s) (%d on disk, %d now). '
             'The jobs are hand-reversed and unrecoverable. Check that the TRUSTS[] regex still matches %s.'
             % (prev_known - have_jobs, prev_known, have_jobs, os.path.relpath(PREV, os.path.join(ROOT, '..'))))
open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
print('gen_trusts: %d trusts -> %s  (%d with a known job, %d job-unknown)' % (len(trusts), os.path.relpath(OUT, os.path.join(ROOT, '..')), have_jobs, len(trusts) - have_jobs))
