#!/usr/bin/env python3
# gen_buff_names.py -- status-id -> display name for the Timers "Duration" column name mode.
# Source res/buffs.lua ({id=.., en="..."}). Output src/model/buffs_gen.h : sorted {id,en} + buff_status_name(id).
import re, os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# res/ lookup with a fallback + env override, the same shape gen_trusts / gen_job_track / gen_overwrites use.
# This was a bare '../../res', which assumed the repo lived inside Windower\plugins\ -- true when it was
# written, false since the repo moved out. The script then died on FileNotFoundError, so buffs_gen.h could not
# be refreshed at all : the next game patch that adds a status id would ship a nameless buff in the Timers
# Duration column, with no working way to regenerate the table.
def find_res():
    cands = []
    env = os.environ.get('WINDOWER_RES')
    if env: cands.append(env)
    cands.append(os.path.join(ROOT, '..', '..', 'res'))
    cands.append(os.path.join(ROOT, 'res'))
    cands.append(os.path.join('D:' + os.sep, 'Windower Tetsouo', 'res'))
    for c in cands:
        if os.path.isfile(os.path.join(c, 'buffs.lua')): return c
    raise SystemExit('res/buffs.lua not found -- set WINDOWER_RES to your Windower res folder')
SRC=os.path.join(find_res(),'buffs.lua')
OUT=os.path.join(ROOT,'src','model','buffs_gen.h')
def cap(s):  # res names are lower-case ("haste") -> Title Case for display
    return ' '.join(w[:1].upper()+w[1:] for w in s.split(' '))
rows={}
for line in open(SRC,encoding='utf-8'):
    m=re.search(r'id=(\d+),en="([^"]*)"',line)
    if m: rows[int(m.group(1))]=cap(m.group(2))
rows=sorted(rows.items())
L=['// buffs_gen.h -- GENERATED by scripts/gen_buff_names.py (res/buffs.lua). status id -> name.',
   '#pragma once','namespace aio {','struct BuffRow { unsigned short id; const char* en; };',
   'static const BuffRow BUFF_NAMES[] = {']
L+= ['    {%d, "%s"},'%(i,n) for i,n in rows]
L+= ['};','static const int BUFF_NAMES_N = %d;'%len(rows),
   'inline const char* buff_status_name(unsigned id) {',
   '    int lo=0, hi=BUFF_NAMES_N-1;',
   '    while (lo<=hi){int m=(lo+hi)>>1; unsigned v=BUFF_NAMES[m].id;',
   '        if(v==id) return BUFF_NAMES[m].en; if(v<id) lo=m+1; else hi=m-1;}',
   '    return 0; }','} // namespace aio']
open(OUT,'w',encoding='utf-8').write('\n'.join(L)+'\n')
print('wrote',OUT,':',len(rows),'buff names')
