#!/usr/bin/env python3
# gen_geo_dur.py -- generate src/model/geo_dur_gen.h from Windower res/item_descriptions.lua.
# Parses every item's in-game description for a native GEO "Indicolure ... duration +N" line (FLAT SECONDS, no %,
# e.g. Bagua Tunic +2 = "Indicolure effect duration +25") and emits an item id -> seconds table.
#
# Universal & future-proof (the game's own item text) : any current/future item with an Indicolure-duration line
# is covered, no hand-maintained list. Wording varies -> "Indicolure spell duration", "Indicolure effect
# duration", "Indicolure duration" ; all mean the same additive seconds on Indi- spells.
#
#   python scripts/gen_geo_dur.py [path-to-res/item_descriptions.lua] > src/model/geo_dur_gen.h
#   (no argument : res\ from $WINDOWER_RES, else the dev install -- genpaths.py)
import os, re, sys
import genpaths

src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(genpaths.res_dir(), "item_descriptions.lua")

# "Indicolure" spell duration +15  /  Indicolure effect duration +25  /  "Indicolure" duration +21
# (the item text quotes Indicolure as escaped \" in the lua -> absorb any [" \] between the words)
DUR = re.compile(r"Indicolure[\"\\]*\s*(?:spell\s+|effect\s+)?duration\s*([+-]\d+)", re.IGNORECASE)
LINE = re.compile(r"\[(\d+)\]\s*=\s*\{id=\d+,en=\"((?:[^\"\\]|\\.)*)\"")

rows = []
for ln in open(src, encoding="utf-8"):
    m = LINE.search(ln)
    if not m:
        continue
    iid = int(m.group(1)); en = m.group(2)
    d = DUR.search(en)
    if not d:
        continue
    sec = int(d.group(1))
    if sec == 0:
        continue
    rows.append((iid, sec))

rows.sort()
out = []
out.append("// geo_dur_gen.h -- GENERATED by scripts/gen_geo_dur.py from Windower res/item_descriptions.lua.")
out.append("// Do NOT hand-edit ; regenerate. item id -> native 'Indicolure ... duration +N' FLAT SECONDS (added to")
out.append("// the Indi- base). Universal / future-proof : covers every item in the game with an Indicolure-duration")
out.append("// line. Included by geo_dur.h as the GEO_DUR_LISTED table.")
out.append("#pragma once")
out.append("namespace aio {")
out.append("struct GeoDurItem { unsigned short id; short sec; };")
out.append("static const GeoDurItem GEO_DUR_LISTED[] = {")
line = "    "
for (i, s) in rows:
    tok = "{%d,%d}," % (i, s)
    if len(line) + len(tok) > 108:
        out.append(line); line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int GEO_DUR_LISTED_N = (int)(sizeof(GEO_DUR_LISTED)/sizeof(GEO_DUR_LISTED[0]));")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d Indicolure-duration items from %s\n" % (len(rows), src))
