#!/usr/bin/env python3
# gen_tb_debuffs.py -- generate src/model/tb_debuff_gen.h from the old AioHUD addon's
# targetbar spell->effect table (vendor/targetbar/tb_spells.lua). Each spell that lands a
# debuff maps to { effectId (FFXI status id), baseDurationSeconds }. This is the AUTHORITATIVE
# list the plugin uses to know, from a 0x028 cast, WHICH debuff a spell applies -- the action
# packet's per-target `param` carries the status for a pure enfeeble but the DAMAGE for a
# nuke/DoT, so we can't trust it blindly ; mapping by SPELL id (animation field) separates
# enfeebles from nukes and yields the base duration for the countdown.
#
#   python scripts/gen_tb_debuffs.py <path-to-tb_spells.lua> > src/model/tb_debuff_gen.h
#
# Nested (multi-effect) spell entries -> the FIRST effect is emitted (the primary debuff).
import re, sys

src = sys.argv[1] if len(sys.argv) > 1 else \
    r"D:\Windower Tetsouo\addons\AioHUD\vendor\targetbar\tb_spells.lua"

# DEBUFF status ids -- the section AFTER the -1 separator in tb_engine.lua's Settings.EffectEnabled.
# Only spells whose landed effect is one of these is a TARGET debuff (excludes Protect/Haste/etc buffs,
# which tb_spells also lists) -- so a buff cast on an ally is never mistaken for a debuff on the mob.
DEBUFF_STATUS = set(
    [10, 2, 3, 4, 11, 13, 5, 6, 7, 12, 21, 28, 31,
     1, 8, 9, 14, 15, 16, 17, 18, 19, 20, 22, 23,
     29, 30,
     128, 129, 130, 131, 132, 133, 134, 135,
     136, 137, 138, 139, 140, 141, 142,
     143, 144, 145, 146, 147, 148, 149,
     155, 156, 157, 158, 159,
     167, 168, 174, 175, 177,
     186, 189,
     192, 193, 194, 217, 223,
     298, 299,
     378, 379, 380]
    + list(range(386, 401)) + [404]
    + list(range(448, 453))
    + [463, 464, 465, 466, 473, 540]
    + list(range(557, 568))
    + [571, 572, 576, 597, 640])

rows = []
line_re = re.compile(r"\[\s*(\d+)\s*\]\s*=\s*(.+?),?\s*(--.*)?$")
for ln in open(src, encoding="utf-8"):
    m = line_re.search(ln)
    if not m:
        continue
    sid = int(m.group(1))
    body = m.group(2).strip()
    if body in ("{}", "nil"):
        continue
    # first pair of numbers inside the (possibly nested) braces = { effect, dur }
    nums = re.findall(r"\d+", body)
    if len(nums) < 2:
        continue
    eff, dur = int(nums[0]), int(nums[1])
    if eff == 0 or eff not in DEBUFF_STATUS:
        continue
    rows.append((sid, eff, dur))

# --- CORRECTIONS ------------------------------------------------------------------------------------------
# Two sources, both wrong, and they disagree with each other : res/spells.lua carries duration=230 for EVERY
# Helix, tier I and tier II alike, and tb_spells.lua (this file's source) inherited 230 for tier I while
# carrying 90 for tier II. The published SCH testing says neither : a Helix runs 30 s at SCH 20-39, 60 s at
# 40-59 and 90 s at 60-99, tier I and tier II the same, lengthened to 168 s by Dark Arts (more under Tabula
# Rasa) and HALVED in place by Modus Veritas. 230 measures nothing.
#
# The corrected value is the level-99 base WITHOUT Dark Arts, deliberately the short end. This number decides
# more than a countdown : debuff_rules.h asks it whether a stronger debuff is still live, and there a value
# that is too LONG refuses a cast the game would accept -- the dangerous direction -- while one that is too
# short only stops protecting early. Dark Arts and Tabula Rasa therefore run past what we claim, harmlessly ;
# Modus Veritas is the one that goes the other way, and it is not modelled yet.
# Source : docs/game-data/reference-sheets/helix.md
CORRECTIONS = {sid: 90 for sid in range(278, 286)}   # Geo/Hydro/Anemo/Pyro/Cryo/Iono/Nocto/Lumino-helix (tier I)
rows = [(s, e, CORRECTIONS.get(s, d)) for (s, e, d) in rows]

rows.sort()
out = []
out.append("// tb_debuff_gen.h -- GENERATED by scripts/gen_tb_debuffs.py from the old AioHUD")
out.append("// targetbar tb_spells.lua. Do NOT hand-edit ; regenerate. spell id -> { status effect id,")
out.append("// base duration seconds }. Used by PartyState::on_action to map a cast (0x028 animation =")
out.append("// spell id) to the debuff it lands -- separates enfeebles from nukes (whose param = damage).")
out.append("#pragma once")
out.append("namespace aio {")
out.append("struct SpellDebuff { unsigned short spell, effect, durSec; };")
out.append("static const SpellDebuff TB_DEBUFFS[] = {")
line = "    "
for i, (s, e, d) in enumerate(rows):
    tok = "{%d,%d,%d}," % (s, e, d)
    if len(line) + len(tok) > 110:
        out.append(line)
        line = "    "
    line += tok
out.append(line)
out.append("};")
out.append("static const int TB_DEBUFFS_N = (int)(sizeof(TB_DEBUFFS)/sizeof(TB_DEBUFFS[0]));")
out.append("// binary search (TB_DEBUFFS is sorted by spell id). Returns 0 if the spell lands no debuff.")
out.append("inline const SpellDebuff* spell_debuff(unsigned spell) {")
out.append("    int lo = 0, hi = TB_DEBUFFS_N - 1;")
out.append("    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = TB_DEBUFFS[mid].spell;")
out.append("        if (s == spell) return &TB_DEBUFFS[mid]; if (s < spell) lo = mid + 1; else hi = mid - 1; }")
out.append("    return 0;")
out.append("}")
out.append("} // namespace aio")
sys.stdout.write("\n".join(out) + "\n")
sys.stderr.write("generated %d debuff-spell rows\n" % len(rows))
