#!/usr/bin/env python3
# gen_overwrites.py -- generate src/model/overwrites_gen.h from res/spells.lua.
#
# res carries, per spell, the list of spell ids that spell OVERWRITES : Dia III (25) has
# overwrites={23,24,230,231} = Dia I, Dia II, Bio I, Bio II. FFXI arbitrates competing debuffs with it :
# a WEAKER spell does not land while a stronger one is up, and a STRONGER one replaces the weaker.
#
# This cannot be inferred from the status id : the rule crosses families (Dia overwrites Bio, they are
# statuses 134 and 135), and it is not a pure tier order either. Used by PartyState::record_debuff, which
# until now refreshed any same-status entry unconditionally -- so a mate's Dia I downgraded your Dia III
# (wrong tier shown AND a 60 s timer instead of 180 s).
#
#   python scripts/gen_overwrites.py [path-to-res-folder]
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def find_res():
    cands = ([sys.argv[1]] if len(sys.argv) > 1 else []) + [
        os.environ.get('FFXI_RES', ''),
        os.path.join(ROOT, '..', '..', 'res'),
        os.path.join(ROOT, 'res'),
        r'D:\Windower Tetsouo\res']
    for c in cands:
        if c and os.path.isfile(os.path.join(c, 'spells.lua')):
            return c
    raise SystemExit('res/spells.lua not found -- pass its folder as argv[1] or set FFXI_RES')

RES = find_res()
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'src', 'model', 'overwrites_gen.h')

rows = []
names = {}
for ln in open(os.path.join(RES, 'spells.lua'), encoding='utf-8', errors='ignore'):
    m = re.search(r'\{id=(\d+),', ln)
    if not m:
        continue
    sid = int(m.group(1))
    en = re.search(r'en="([^"]*)"', ln)
    names[sid] = en.group(1) if en else ''
    ow = re.search(r'overwrites=\{([0-9,\s]*)\}', ln)
    if not ow:
        continue
    ids = sorted(set(int(x) for x in ow.group(1).split(',') if x.strip()))
    if ids:
        rows.append((sid, ids))
rows.sort()
if not rows:
    raise SystemExit('no `overwrites` field found in res/spells.lua -- wrong res version?')
MAXN = max(len(r[1]) for r in rows)

# --- the -ga hole -------------------------------------------------------------------------------------------
# res gives the single-target ladder exactly right (Bio II overwrites Dia I AND Dia II, Dia III overwrites Bio
# I/II, ...) but lists NOTHING for the AoE forms : Diaga I-V appear in no `overwrites` field, neither as the
# overwriter nor as the overwritten. The game, though, treats them as the same spell : "Diaga is treated as the
# same as Dia -- Dia II will override Diaga, but not the other way around". Left alone, a Diaga I lands on a mob
# holding Dia II and simply refreshes it (both are status 134), silently DOWNGRADING the tier we show.
# So map every "-ga" spell onto its single-target twin by NAME ("Diaga III" -> "Dia III") and canonicalise both
# sides of the test. Kept general rather than a Dia special case : Sleepga/Poisonga/... have the same shape.
by_name = {}
for sid, nm in names.items():
    if nm:
        by_name.setdefault(nm, sid)
involved = set(s for s, _ in rows)
for _s, ids in rows:
    involved.update(ids)
alias = {}
for sid, nm in names.items():
    m = re.match(r'^(.+?)ga((?: (?:II|III|IV|V))?)$', nm or '')
    if not m:
        continue
    twin = by_name.get(m.group(1) + m.group(2))
    if twin and twin != sid and twin in involved:   # only where the twin actually takes part in the ladder
        alias[sid] = twin

L = ['// overwrites_gen.h -- GENERATED by scripts/gen_overwrites.py from res/spells.lua. Do NOT hand-edit.',
     '// spell id -> the spell ids it OVERWRITES. FFXI refuses a weaker debuff while a stronger one is up, and',
     '// replaces the weaker one when the stronger lands. The relation CROSSES families (Dia III overwrites Bio I/II),',
     '// so it cannot be derived from the status id. Consumed by PartyState::record_debuff.',
     '#pragma once',
     'namespace aio {',
     'struct SpellOverwrite { unsigned short spell; unsigned char n; unsigned short list[%d]; };' % MAXN,
     'static const SpellOverwrite SPELL_OVERWRITES[] = {']
for sid, ids in rows:
    pad = ids + [0] * (MAXN - len(ids))
    L.append('    {%d,%d,{%s}},   // %s' % (sid, len(ids), ','.join(str(x) for x in pad), names.get(sid, '')))
L += ['};',
      'static const int SPELL_OVERWRITES_N = (int)(sizeof(SPELL_OVERWRITES)/sizeof(SPELL_OVERWRITES[0]));',
      '// binary search (sorted by spell id). 0 = this spell overwrites nothing.',
      'inline const SpellOverwrite* spell_overwrites(unsigned spell) {',
      '    int lo = 0, hi = SPELL_OVERWRITES_N - 1;',
      '    while (lo <= hi) { int mid = (lo + hi) >> 1; unsigned s = SPELL_OVERWRITES[mid].spell;',
      '        if (s == spell) return &SPELL_OVERWRITES[mid]; if (s < spell) lo = mid + 1; else hi = mid - 1; }',
      '    return 0;',
      '}',
      '// AoE (-ga) form -> its single-target twin. res lists no `overwrites` for them, but the game treats them as',
      '// the same spell ("Dia II overrides Diaga, but not the other way around"), so both sides of a comparison are',
      '// canonicalised through this first. Without it a Diaga I silently downgraded a Dia II (same status 134).',
      'struct SpellAlias { unsigned short spell, same; };',
      'static const SpellAlias OW_ALIAS[] = {']
for _s in sorted(alias):
    L.append('    {%d,%d},   // %s -> %s' % (_s, alias[_s], names.get(_s, ''), names.get(alias[_s], '')))
L += ['};',
      'static const int OW_ALIAS_N = (int)(sizeof(OW_ALIAS)/sizeof(OW_ALIAS[0]));',
      'inline unsigned ow_canonical(unsigned spell) {',
      '    for (int i = 0; i < OW_ALIAS_N; ++i) if (OW_ALIAS[i].spell == spell) return OW_ALIAS[i].same;',
      '    return spell;',
      '}',
      '// does spell `a` overwrite spell `b` ? (false when they resolve to the SAME spell : a recast, or the AoE form',
      '// of what is already up, is a refresh -- not an overwrite)',
      'inline bool spell_overwrites_spell(unsigned a, unsigned b) {',
      '    a = ow_canonical(a); b = ow_canonical(b);',
      '    if (!a || !b || a == b) return false;',
      '    const SpellOverwrite* o = spell_overwrites(a);',
      '    if (!o) return false;',
      '    for (int i = 0; i < o->n; ++i) if (o->list[i] == b) return true;',
      '    return false;',
      '}',
      '} // namespace aio']
open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('wrote %s : %d spells with overwrites, max list %d' % (OUT, len(rows), MAXN))
