#!/usr/bin/env python3
# gen_resistances.py -- generate src/model/resistances_gen.h from the SheolHelper Lua data tables.
#
# Sources (reference addon, kept locally):
#   addons/sheolhelper/resistances.lua  -- per mob-family : 12 values {Slsh,Pierc,Blunt,Joke,Fire,Ice,Wind,Earth,Thunder,Water,Light,Dark}
#   addons/sheolhelper/types.lua        -- per mob-type   : {weapon, family1, family2, ...}  (weapon = Slashing/Piercing/Blunt/Magic/Unknown)
#   addons/AioHUD/modules/sheolhelper.lua -- joke_by_zone : per family, Cruel-Joke vulnerability in Sheol B(2)/C(3)
#
# Output rows are sorted by family name for a binary search in C++ (res_lookup).
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# addons/ lookup with a fallback + env override, like the res/ lookups elsewhere in scripts/. The bare
# '../../addons' assumed the repo sat inside Windower\plugins\ ; since the repo moved out it resolves to a
# folder that does not exist, so this generator could not run at all. It still needs the SheolHelper addon to
# be installed -- there is no other source for these tables -- but it now SAYS that instead of dying on a path.
def find_addons():
    cands = []
    env = os.environ.get('WINDOWER_ADDONS')
    if env: cands.append(env)
    cands.append(os.path.join(ROOT, '..', '..', 'addons'))
    cands.append(os.path.join('D:' + os.sep, 'Windower Tetsouo', 'addons'))
    for c in cands:
        if os.path.isfile(os.path.join(c, 'sheolhelper', 'resistances.lua')): return c
    raise SystemExit('addons/sheolhelper/resistances.lua not found -- install the SheolHelper addon, '
                     'or set WINDOWER_ADDONS to your Windower addons folder')
ADDONS = find_addons()
RES_LUA  = os.path.join(ADDONS, 'sheolhelper', 'resistances.lua')
TYPE_LUA = os.path.join(ADDONS, 'sheolhelper', 'types.lua')
JOKE_LUA = os.path.join(ADDONS, 'AioHUD', 'modules', 'sheolhelper.lua')
OUT = os.path.join(ROOT, 'src', 'model', 'resistances_gen.h')

WEAPON = {'Slashing': 0, 'Piercing': 1, 'Blunt': 2, 'Magic': 3, 'Unknown': 4}

def read(p):
    with open(p, 'r', encoding='utf-8') as f:
        return f.read()

# ---- resistances.lua : ['Family'] = {v1, ..., v12}, ----
res = {}
for m in re.finditer(r"\['([^']+)'\]\s*=\s*\{([^}]*)\}", read(RES_LUA)):
    name = m.group(1)
    if name == 'Legend':
        continue
    nums = re.findall(r"[-+]?\d*\.?\d+", m.group(2))
    if len(nums) < 12:
        continue
    res[name] = [int(round(float(x) * 1000)) for x in nums[:12]]   # store x1000 (increments of 0.125 -> exact)

# ---- types.lua : ['Type'] = {'Weapon', 'Fam', ...} -> family -> weapon-type index ----
fam_wtype = {}
for m in re.finditer(r"\['([^']+)'\]\s*=\s*\{([^}]*)\}", read(TYPE_LUA)):
    items = re.findall(r"'([^']*)'", m.group(2))
    if not items:
        continue
    wt = WEAPON.get(items[0], 4)
    for fam in items[1:]:
        fam_wtype[fam] = wt

# ---- joke_by_zone (AioHUD) : ['Family'] = {[2] = bool, [3] = bool} ----
joke = {}
jb = read(JOKE_LUA)
jstart = jb.find('joke_by_zone')
jbody = jb[jstart: jb.find('}', jb.find('{', jstart))] if jstart >= 0 else ''
# match: ['Family'] = {[2] = true, [3] = false}
for m in re.finditer(r"\['([^']+)'\]\s*=\s*\{\s*\[2\]\s*=\s*(true|false)\s*,\s*\[3\]\s*=\s*(true|false)\s*\}", jb):
    joke[m.group(1)] = (1 if m.group(2) == 'true' else 0, 1 if m.group(3) == 'true' else 0)

rows = []
for fam in sorted(res.keys()):
    v = res[fam]
    wt = fam_wtype.get(fam, 4)             # families absent from types.lua -> Unknown weapon
    jb_, jc_ = joke.get(fam, (-1, -1))     # -1 = no zone override (fall back to v[3] != 0)
    rows.append((fam, v, wt, jb_, jc_))

lines = []
lines.append('// resistances_gen.h -- GENERATED by scripts/gen_resistances.py from the SheolHelper Lua tables. Do NOT hand-edit.')
lines.append('// Per mob family: 12 resistance values x1000 (Slsh,Pierc,Blunt,Joke,Fire,Ice,Wind,Earth,Thunder,Water,Light,Dark),')
lines.append('// the type WEAPON (0 Slashing,1 Piercing,2 Blunt,3 Magic,4 Unknown), and Cruel-Joke vulnerability per Sheol B/C')
lines.append('// (jokeB/jokeC: -1 no zone override -> use v[3]!=0, else 0 immune / 1 vulnerable). Binary-searched by res_lookup.')
lines.append('#pragma once')
lines.append('namespace aio {')
lines.append('struct ResRow { const char* family; short v[12]; unsigned char wtype; signed char jokeB, jokeC; };')
lines.append('static const ResRow RES_ROWS[] = {')
for fam, v, wt, jb_, jc_ in rows:
    vs = ','.join('%d' % x for x in v)
    lines.append('    { "%s", {%s}, %d, %d, %d },' % (fam, vs, wt, jb_, jc_))
lines.append('};')
lines.append('static const int RES_ROWS_N = %d;' % len(rows))
lines.append('} // namespace aio')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print('wrote %s : %d families' % (OUT, len(rows)))
